### ISSUE TITLE
Start radio function

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#10]
![174492302-a4b1f05f-db17-4885-90c2-8b805db895b4](https://github.com/maxrave-dev/SimpMusic/assets/103368536/ef0c7770-331d-412d-be93-35b34024de9b)

**Comment by maxrave-dev** [comment]
When you play a track, the radio is playing right now, check the list of tracks in Queue Button in Now Playing Screen

<img src="https://lh3.googleusercontent.com/pw/AIL4fc-ih3PRzIL7yvXL2FkgawBJBA-mX7OwTbQk5pO2CNj691OuvGA3PD5VHnA2jQ_RAUhjzx-GQ7Y4yLZhPoducoEJ3dHOOyMm_Zzj_mAuIwINxdfybVRa8HOB1WNxGE2ya91UDy6--Nvj6miW2jzkMKLPFQ=w429-h929-s-no?authuser=0">

**Comment by siggi1984** [comment]
Sorry, did not see it.
