### ISSUE TITLE
bottom navigation bar not working properly

### ISSUE THREAD

**Issue by SidharthMudgil** [maxrave-dev/SimpMusic#106]
**Describe the bug**
active item not showing as it should be in bottom navigation view

**To Reproduce**
1. In home go to settings
2. go to search
3. go back to home, it will still show search as active item.

Also same for other fragments in library.

**Expected behavior**
On clicking back on the home item in bottom navigation view it should show home as active item.

**Screenshots**

https://github.com/maxrave-dev/SimpMusic/assets/68889544/59d59cc8-22e5-480c-b185-f89ce55586ec

**Comment by SidharthMudgil** [comment]
If you allow, I can work on this issue. Assign me

**Comment by maxrave-dev** [comment]
> If you allow, I can work on this issue. Assign me

Thanks for your report, if you want to contribute, please folk "dev" branch and create a pull request to "dev" branch. Thanks so much 😍
