### ISSUE TITLE
Song never start

### ISSUE THREAD

**Issue by 6801318d8d** [maxrave-dev/SimpMusic#112]
1. Search for "I funerali di Berlinguer"
2. Click on first search result (author: Modena City Ramblers, album: Riportando tutto a casa)
3. The song never starts. The loading bar loops forever

This is an Italian communist song. The Party would be very delighted to hear it.

**Comment by 6801318d8d** [comment]
here is the cover

![Screenshot_20231007-094116_SimpMusic_1](https://github.com/maxrave-dev/SimpMusic/assets/144167388/e5a48db2-0884-499d-8c9d-212ff09ecb7d)

**Comment by maxrave-dev** [comment]
I don't see this track in my location. Can you check YouTube Music with this song?

**Comment by 6801318d8d** [comment]
> I don't see this track in my location. Can you check YouTube Music with this song?

https://music.youtube.com/watch?v=_NnRhc7_Irw&feature=shared

**Comment by stepersy** [comment]
I tried it now, and for me it works. Probably the problem is yours...
![Screenshot_20231012-235219_Pixel Launcher.png](https://github.com/maxrave-dev/SimpMusic/assets/94073410/27ce56ee-48d1-4bee-8c75-9b120c32a9d6)

**Comment by maxrave-dev** [comment]
@6801318d8d try 0.1.4 version

**Comment by 6801318d8d** [comment]
> @6801318d8d try 0.1.4 version

It's not on F-Droid yet

**Comment by stepersy** [comment]
Install it from GitHub, it's the same

**Comment by 6801318d8d** [comment]
> Install it from GitHub, it's the same

I installed 0.1.4 from GitHub, it plays correctly now. Thanks :)
