### ISSUE TITLE
No showing all albums from artists

### ISSUE THREAD

**Issue by dainvincible1** [maxrave-dev/SimpMusic#114]
Only 10 albums are shown when i search for an artist. If an artist has more than 10 albums, its not shown

https://github.com/maxrave-dev/SimpMusic/assets/127825700/30e28c2c-f818-4439-84a4-5a8a213f98cd

Like this artist "taylor sswift" has more than 10 albums but only 10 are shown here.

**Comment by baruchin** [comment]
I can confirm this. The app is unusable for me with this bug.

**Comment by maxrave-dev** [comment]
I see this. Like YouTube Music, only return maximum 10 albums in artist page. But YouTube Music have show more button. I will implement it to the next build. Thanks for reporting

**Comment by baruchin** [comment]
> I see this. Like YouTube Music, only return maximum 10 albums in artist page. But YouTube Music have show more button. I will implement it to the next build. Thanks for reporting

Thank you.
