### ISSUE TITLE
Player bug 

### ISSUE THREAD

**Issue by AanooBeta** [maxrave-dev/SimpMusic#12]
I don't it is implemented that way but in player it shows this :
![Screenshot_20230802-154955_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/108539997/9a934a1a-08b2-4e96-9686-31240e4a8fa1)
The icon are not visible fully without scrolling down

**Comment by maxrave-dev** [comment]
It is UI problem, i try to fix it, thanks for your report

**Comment by BluePixel4k** [comment]
@maxrave-dev any news for a fix? I have the same problem on my phone.
Thx :)

**Comment by BluePixel4k** [comment]
Thx, but I will wait for the release with the adaptation for smaller screens.
