### ISSUE TITLE
Wrong Lyrics

### ISSUE THREAD

**Issue by Paxsenix0** [maxrave-dev/SimpMusic#120]
**Describe the bug**
Bugs when getting lyrics, it's showing the wrong lyrics. maybe you can tried to use `duration` value to match the lyrics with the songs :)

**To Reproduce**
1. Go to 'Library'
2. Click on 'Songs (Christmas kids - Roar, Disenchanted - My Chemical Romance)'
3. Scroll down to 'Lyrics'
4. See bugs

> Example: 
[Christmas kids - Roar](https://youtube.com/watch?v=u6m0ymy2oFk)
[Disenchanted - My Chemical Romance](https://youtube.com/watch?v=95hfNjZictY)

**Screenshots**
## Wrong lyrics
![Screenshot_20231011-232246.jpg](https://github.com/maxrave-dev/SimpMusic/assets/126800641/fee21758-3a67-4323-8e1d-2d72246a31de)

## Right lyrics
![Screenshot_20231011-232638.jpg](https://github.com/maxrave-dev/SimpMusic/assets/126800641/d01b3531-810e-493f-93d3-d7827382f85d)

**Comment by maxrave-dev** [comment]
Too hard to say 100% lyrics matched perfectly. It's depend on Musixmatch searching API. I am trying to improve the engine. Thanks for reporting <3

**Comment by Paxsenix0** [comment]
> Too hard to say 100% lyrics matched perfectly. It's depend on Musixmatch searching API. I am trying to improve the engine. Thanks for reporting <3

You're welcome! ;D

**Comment by Paxsenix0** [comment]
Hello!

Try this musixmatch api url
`https://apic-desktop.musixmatch.com/ws/1.1/macro.subtitles.get?format=json&namespace=lyrics_richsynched&subtitle_format=mxm&app_id=web-desktop-app-v1.0`

and need parameter:
`usertoken` **user token**
`q_artist` **Artist name**
`q_track` **Title**
`q_duration` **Duration**

This can help you to get more accurate lyrics;)

**Comment by kemekelen** [comment]
Here it is correct but not sync, lyric always scrolled too fast. Tried to turn off "skip silent" but problem persisted.
