### ISSUE TITLE
SO LAGGING 

### ISSUE THREAD

**Issue by Slient1802** [maxrave-dev/SimpMusic#13]
# I have been waiting for 30min but the software can't load any song ╰（‵□′）╯
![lag](https://github.com/maxrave-dev/SimpMusic/assets/97616140/d2aef802-c12a-4a38-8f58-7e836f3e8a97)

**Comment by maxrave-dev** [comment]
Please download my newest build to fix this. I change hosting server because old server became overloading when have too much request

**Comment by Slient1802** [comment]
I have installed version 0.0.3 but it still doesn't work, it even crash a lot (*￣_￣)╭ , and seems the app doesn't have suggestions song based on my list of song, I have to manually select the song, kinda somewhat annoyed (ง •_•)ง  btw thank you for open-source this app §(*￣▽￣*)§

**Comment by maxrave-dev** [comment]
https://github.com/maxrave-dev/SimpMusic/releases/tag/v0.0.3-beta use this version to fix lag. By the way, my app uses client-server architecture so sometimes it will be lagging. I am trying to create a self-scrape YouTube Music, and update you soon. Thanks for your support <3
