### ISSUE TITLE
Connection problem while playing downloaded music

### ISSUE THREAD

**Issue by Zoura007** [maxrave-dev/SimpMusic#132]
While playing downloaded song specifically james Arthur's impossible the song stops at 1:42 and says time out check internet connection when it is clearly downloaded and wifi is closed even if its not closed its the same

**To Reproduce**
1. Search for 'james Arthur impossible'
2. Download the song
3. Close your wifi or data
4. Play the song without skipping till 1:42

**Expected behavior**
If its downloaded then there should be no reason for connection issue so the song should be playing without any interruption

**Screenshots**
![Screenshot_20231018-173114.jpg](https://github.com/maxrave-dev/SimpMusic/assets/128911783/f567ea2f-7189-4cb4-982f-093cca6b7d05)

**Comment by maxrave-dev** [comment]
Removed this download and download again. Does it work?

**Comment by Zoura007** [comment]
Nope
