### ISSUE TITLE
[Feature Request] Add Android 11+ media resumption support

### ISSUE THREAD

**Issue by Ciancy28** [maxrave-dev/SimpMusic#133]
https://developer.android.com/media/implement/surfaces/mobile?hl=en#supporting-media

This would allow users to quickly resume playback from the notification shade even after closing the app 

Most music streaming apps including Spotify and YouTube Music already support this, but it's currently not implemented in SimpMusic

**Comment by maxrave-dev** [comment]
why did you want to play music when close app?

**Comment by teemue** [comment]
Hope this gets implemented

**Comment by maxrave-dev** [comment]
Done
