### ISSUE TITLE
Casting function

### ISSUE THREAD

**Issue by Terkyz** [maxrave-dev/SimpMusic#135]
**Is your feature request related to a problem? Please describe.**
No, not at all. But this is an absolutely great feature that Spotify has and I want to introduce SimpMusic to a person who doesn't know much about technology and that person usually uses the cast feature to play Youtube music on their Smart TV (I guess as some people do the same with their Bluetooth speakers) and I think that would be a feature that person would love if it was implemented in SimpMusic.

**Describe the solution you'd like**.
A button to share music from SimpMusic to a SmartTV or Chromecast.

**Describe alternatives you've considered**.
At the moment just nothing, I really don't think there is any Youtube Music app with this feature.

**Additional context**
I think it would be a good idea if the button was in the main menu and when you are inside a song, Netflix style.

**Comment by Terkyz** [comment]
Regarding issue #158 my intention was not to add proprietary libraries to SimpMusic, but apps like [CloudStream](https://github.com/recloudstream/cloudstream) have the ability to cast (and without adding proprietary libraries, as far as I understand) so I thought it was possible.

**Comment by maxrave-dev** [comment]
> Regarding issue #158 my intention was not to add proprietary libraries to SimpMusic, but apps like [CloudStream](https://github.com/recloudstream/cloudstream) have the ability to cast (and without adding proprietary libraries, as far as I understand) so I thought it was possible.

https://github.com/recloudstream/cloudstream/blob/master/app/build.gradle.kts#L186-L186

Did you know what proprietary libraries are?

**Comment by Terkyz** [comment]
Unfortunately I can't even find information about it in CloudStream's Github, but doing some research I found that MicroG [has a variant for open source casting](https://github.com/microg/GmsCore/tree/master/play-services-cast-api), although unfortunately the link doesn't seem to lead anywhere.
