### ISSUE TITLE
When starting the radio mode, merge the song being played with the radio mode playlist

### ISSUE THREAD

**Issue by Terkyz** [maxrave-dev/SimpMusic#136]
**Is your feature request related to a problem? Please describe.
Yes, when I'm listening to a song and I start the radio mode and I want to change to another song I need to press on a song from the playlist created, I think it would be logical that pressing the button to change the song would change to another song from the playlist created for the radio mode.

**Describe the solution you'd like**.
As I mentioned, the song that is playing at the moment of activating the radio mode is recognized as part of the playlist of the radio mode.

**Describe alternatives you've considered**
Play any song from the playlist.

**Additional context**.
Thanks for your work!

**Comment by maxrave-dev** [comment]
Nice idea
