### ISSUE TITLE
Playlist Sort

### ISSUE THREAD

**Issue by DeadSecTr** [maxrave-dev/SimpMusic#139]
Please provide a way to sort the songs in the playlist by newest/oldest (local & YouTube online).

**Comment by maxrave-dev** [comment]
I have implemented a function to arrange the latest track to the last of the playlist instead of sorting with inLibrary time

https://github.com/maxrave-dev/SimpMusic/assets/113747128/a8500375-db4d-4e21-9e2a-1cf5c8067ff2

Do you think it resolved this issue? @DeadSecTr

**Comment by DeadSecTr** [comment]
I will like it personaly more when the newest songs are at the top of the list...so there where no need to scroll down everytime

**Comment by maxrave-dev** [comment]
Add a button "Newest/Oldest" ?

**Comment by DeadSecTr** [comment]
Yes bro,like the original youtube app.

Btw..thank you for the great app
