### ISSUE TITLE
Lyrics isn't visible in lyrics tab

### ISSUE THREAD

**Issue by sujitfg1** [maxrave-dev/SimpMusic#145]
### Lyrics Visibility Issue
When we are listening to some song (here "Chaleya") the lyrics isn't visible in lyrics tab. Lyrics tab is blank !

I expect to see**
Lyrics tab should be visible in simpmusic as it's visible in Spotify but its blank

Screenshot to bug
![Screenshot_20231102_003926](https://github.com/maxrave-dev/SimpMusic/assets/105970492/623b7862-9926-4ce8-974e-b947fbc3eee6)

I was also listening "METRO BOOMIN PRESENTS SPIDER-MAN: ACROSS THE SPIDER-VERSE" Where Lyrics is visible in Spotify
![Screenshot_20231102_004727](https://github.com/maxrave-dev/SimpMusic/assets/105970492/5757a415-4c84-4a09-ab89-ecf6092ed6ee)
 but the lyrics tab is completely disabled in Simpmusic!?
![Screenshot_20231102_004752](https://github.com/maxrave-dev/SimpMusic/assets/105970492/d9b17fd6-a922-4b95-bae8-4a345c098ca9)

**Comment by maxrave-dev** [comment]
Better lyrics search algorithm in next version. v0.1.5 will be fixed
![Screenshot_20231102-123706_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/9344747d-dc90-4ee6-86e3-f5738a370250)

![Screenshot_20231102-123745_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/48f54ccb-0bb4-4351-a97b-a797c589a29b)

**Comment by sujitfg1** [comment]
That's great 👍. Thnx dev ❤️
