### ISSUE TITLE
song skipping

### ISSUE THREAD

**Issue by senolfndk** [maxrave-dev/SimpMusic#151]
jumping is too slow

**Comment by DeadSecTr** [comment]
Ehm...nope..for me its fine! Maybe slow internet/wifi?!

**Comment by senolfndk** [comment]
> Ehm...hayır..benim için sorun değil! Belki yavaş internet/wifi?!

internet speed is stable

**Comment by DeadSecTr** [comment]
and fast?

**Comment by senolfndk** [comment]
> ve hızlı?

yes
