### ISSUE TITLE
[Idea/Request] Spotify-style video playback in portrait mode

### ISSUE THREAD

**Issue by Terkyz** [maxrave-dev/SimpMusic#167]
**Is your feature request related to a problem? Please describe.
No. Currently the way it works is fine, but it seems to me that for aesthetic reasons it looks better the way Spotify does it. Spotify as such does not play videos, obviously, but in some songs it has a kind of gif/video that plays and loops in the background, it would be great if the videos would play like that in SimpMusic.

**Describe the solution you'd like**.
When accessing a music video in SimpMusic, play the video vertically with enough zoom to cover the entire screen, and have a button for "landscape mode" where it plays in full screen.

**Describe alternatives you've considered
None really, I only came up with this recently with the release of 0.1.6.

**Additional context**
It's ok if it's not accepted, but I think it would look cool with such a feature.

**Comment by maxrave-dev** [comment]
Spotify has a feature named Canvas, a short video play background, but in YouTube Music can't find any like this. Any suggest for me?

**Comment by Terkyz** [comment]
Hmm, not really... It occurs to me that SM could bring by default some looping videos and let the user choose which one he wants to choose for his songs, or import a new one, but I don't know if it's really necessary.

Also what I already said about rescaling and cropping the original playback video to the dimensions of the device screen, but I don't know if it's possible.
