### ISSUE TITLE
[Feature request] Keeping the music playing when the app is closed

### ISSUE THREAD

**Issue by Terkyz** [maxrave-dev/SimpMusic#168]
**Is your feature request related to a problem? Please describe.
Not necessarily, because I can just not close the app anyway, but it would be great if the music would continue when the app is closed.

**Describe the solution you'd like**.
When I close the app, the song that is playing continues to play normally, and that if I remove the notification that indicates the song that is playing the song stops.

**Describe alternatives you've considered
I can just turn off the screen and that's it.

**Additional context**
Thanks for your work.

**Comment by maxrave-dev** [comment]
Done
