### ISSUE TITLE
the song doesn't play until the end

### ISSUE THREAD

**Issue by VitaliiLesko** [maxrave-dev/SimpMusic#172]
**Describe the bug**

https://youtu.be/bYh28VkDeVM

this song doesn't play until the end, always stopped in 3:22. Why?

**Comment by maxrave-dev** [comment]
![Screenshot_20231117-200224_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/885a5742-cf69-45d4-a04a-7535600fd26a)

In my case, it still play. Try to remove player cache

**Comment by VitaliiLesko** [comment]
Yes, thank you it worked.
