### ISSUE TITLE
SimpMusic 0.1.6 - Bug in Youtube API

### ISSUE THREAD

**Issue by ghost** [maxrave-dev/SimpMusic#176]
Hello, I was using 0.1.5 and today I updated to the new version 0.1.6 from 
https://github.com/maxrave-dev/SimpMusic/releases/download/v0.1.6/SimpMusic_v0.1.6.apk

I have a Xiaomi smartphone with MIUI 12.0.11 (Android 10). 

Unfortunately the app is not working anymore. You can see the printscreen here (the app is in brazilian portuguese, because I am from Brazil):

![photo1700521985](https://github.com/maxrave-dev/SimpMusic/assets/3200574/657ea2dc-d098-4fe5-bf4f-50477e2fb472)
![photo1700521883 (1)](https://github.com/maxrave-dev/SimpMusic/assets/3200574/5690de60-66d5-467a-8511-743f14aa05f8)
![photo1700521883](https://github.com/maxrave-dev/SimpMusic/assets/3200574/f7cbb10e-0000-4f18-9c04-ca44fdb17c6a)

**Comment by maxrave-dev** [comment]
Use VPN may be fixed

**Comment by stepersy** [comment]
I had the same version after updating the app. Try clearing the cache, uninstall and reinstall, switch on and off the airplane mode. For me it worked. Let me know

**Comment by unknoxx** [comment]
Having the same problem and I've tried all method it'll work but immediately you close the app and open it again the same problem starts again, this is my first time using the app and the experience is not fine, I'll try the precedent version.

**Comment by maxrave-dev** [comment]
> Having the same problem and I've tried all method it'll work but immediately you close the app and open it again the same problem starts again, this is my first time using the app and the experience is not fine, I'll try the precedent version.
> 
> EDIT: even the previous version is having the same issue

May be you install some untrust certificates to your phone or your network is not trust, so YouTube refused your request or may be your country is not supported YouTube Music

**Comment by unknoxx** [comment]
> > Having the same problem and I've tried all method it'll work but immediately you close the app and open it again the same problem starts again, this is my first time using the app and the experience is not fine, I'll try the precedent version.
> > 
> > EDIT: even the previous version is having the same issue
> 
> May be you install some untrust certificates to your phone or your network is not trust, so YouTube refused your request or may be your country is not supported YouTube Music

My country supports YT music and I didn't install any form of untrusted certificate

**Comment by DeadSecTr** [comment]
Please dudes.....its a bug! Thats the point!
