### ISSUE TITLE
"android.hardware.type.automotive" required

### ISSUE THREAD

**Issue by kiwipedio** [maxrave-dev/SimpMusic#177]
I'm still using ver. 1.4 beta because I'm unable to download ver. 1.5 /1.6 from F-droid by android.hardware.type.automotive missing. 

Downloading and installing v.1.6 from Github is possible but the app returns unidentified network error. I don't know if it's always related to android.hardware.type.automotive missing.

I was forced to downgrade to ver. 1.4 beta.

![Screenshot_2023-11-21-10-27-08-33_bf5286d428c97f865e4b51a5afbaefcd](https://github.com/maxrave-dev/SimpMusic/assets/150342235/32b4aa42-fd8e-4997-a4f9-38a6f0a51ec1)

**Comment by stepersy** [comment]
Which Version of Android do you have?

**Comment by kiwipedio** [comment]
- Oppo A9 2020 with ColorOS 7.1 (Android 10) last patch available and installed CPH1941EX_11_C.88 (May 2021)
- ROM is native, no root, shizuku or somelse
- Android Auto natively installed but not updated; I don't want update it because I can't downgrade after installation; Play's reviews warns about it in addition to the worst use.

I don't need to use SimpMusic on my car so is it possible that the app cannot be installed for so foolish thing?
