### ISSUE TITLE
Content not working 

### ISSUE THREAD

**Issue by MrConqueror** [maxrave-dev/SimpMusic#18]
![IMG_20230803_225832](https://github.com/maxrave-dev/SimpMusic/assets/102837820/602c605c-5075-449f-a88f-26668557a902)
i chose PH content but it seems doesn't work, Hopefully we can choose what music county we want to appear on homepage.

Good app Tho very nice UI and Player it's clean like Spotify compared to Music Player of other app on Playstore they too extra that's why i like Spotify like player and this one.

**Comment by maxrave-dev** [comment]
Fix all lagging caused by server in version 0.1.0-beta. Check out my latest build. Thank you so much

**Comment by MrConqueror** [comment]
> Fix all lagging caused by server in version 0.1.0-beta. Check out my latest build. Thank you so mu

> Fix all lagging caused by server in version 0.1.0-beta. Check out my latest build. Thank you so much

Cool, anyway i wish someday maybe you could do something regarding the content country not working.

**Comment by maxrave-dev** [comment]
Working but you see Youtube Music only changed Quick Picks when change content country. If you want to change all contents, you need to use VPN.
