### ISSUE TITLE
Client request bug? 

### ISSUE THREAD

**Issue by unknoxx** [maxrave-dev/SimpMusic#180]
**Describe the bug**
Client request pop up notification after opening the app (check image) 

**To Reproduce**
1. Open the app 

**Expected behavior**
Expecting the app to work as normal

**Screenshots**
![Screenshot_20231123_150156_com.maxrave.simpmusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/81586558/0757f75a-564b-4a80-8a00-0d8055098082)

**Comment by jakesunplugged** [comment]
Same problem for me.

**Comment by CarameruScotch** [comment]
I'm also facing the same issue

![simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/138018454/6657a7da-82a0-4133-a95b-019158b6a0d4)

**Comment by notquarks** [comment]
Selecting content country seems to fix the issue, but you have to do it every time you launch your app

**Comment by unknoxx** [comment]
> Selecting content country seems to fix the issue, but you have to do it every time you launch your app

That's a pain doing that,  I also tried taking the big step logging in with YT,  thought it works until i closed the app and reopen it,  i decided to opt in for other options.

**Comment by jakesunplugged** [comment]
Reinstalled. Works now.

**Comment by unknoxx** [comment]
> Reinstalled. Works now.



> Reinstalled. Works now.

Late reply but does it still work?

**Comment by jakesunplugged** [comment]
> Late reply but does it still work?

Yes, it does. Turning out to be a fun app.
