### ISSUE TITLE
Fdroid Version?

### ISSUE THREAD

**Issue by DeadSecTr** [maxrave-dev/SimpMusic#181]
The last update is not on Fdroid shown

**Comment by yonoff** [comment]
The new version appears as incompatible version in droidify app, unable to install. I downloaded and installed it from the fdroid website using a browser. Works fine on pixel 4a (android 13)

![Screenshot_20231124-212423_Trebuchet](https://github.com/maxrave-dev/SimpMusic/assets/9549832/fe469020-d65a-4157-bed8-8e7f7bf2f231)

**Comment by DeadSecTr** [comment]
Oh ok thanks

**Comment by kiwipedio** [comment]
I noticed the same issue at
"android.hardware.type.automotive" required

**Comment by DarkCrypt** [comment]
Issue #158 is the cause.
