### ISSUE TITLE
Save Downloads to Local Storage instead of Cache

### ISSUE THREAD

**Issue by AJRadaza** [maxrave-dev/SimpMusic#186]
The first time I used the app, I was so excited because the download feature works and it's also fast. The problem is I searched for the downloaded files and I noticed they're only saved in the app's cache and not accessible to other apps like Poweramp. I also use a temporary files cleaner app and it clears the Download cache of SimpMusic.

I think it would be better if the downloaded music files and playlists are saved to the Local Storage to solve this problem. 

Would be best if the Music files are embedded with Album Art, Metadata and Lyrics. Also saving the playlists as .m3u files, and the music files as .m4a.

**Comment by Sensex00** [comment]
Hey anybody have not answered it yet but I think your problem cannot be solved because because for offline playback it only dependent on cache like any other yt music player vimusic, innertune , 
It cannot show downloaded songs as files for other apps to access. Hope you get my point.

**Comment by maxrave-dev** [comment]
I do not plan to make my app a Music Downloader
