### ISSUE TITLE
Cast & local media add

### ISSUE THREAD

**Issue by ZixX3r** [maxrave-dev/SimpMusic#189]
Support for casting your audio through Chromecast would be amazing! I currently have SimpMusic as my main music player, yet when I want to cast music on my "Smart" speakers, I have to use another app, which can't locate my downloaded SimpMusic library. Also as other users asked, the ability to add our local media into the player, hopefully in a file-tree way, as in (Artist Folder> Album folder> songs.mp3) to keep things organize. 
One last question, where are the files downloaded saved? I'm in Android 14. 
Thank you! And again this player is amazing.

**Comment by maxrave-dev** [comment]
Not plan to use ChromeCast
