### ISSUE TITLE
Add crashlytics

### ISSUE THREAD

**Issue by dattran2k** [maxrave-dev/SimpMusic#19]
You may add crashlytics to tracking app crash

**Comment by airon90** [comment]
If necessary, please use a FOSS alternative

**Comment by maxrave-dev** [comment]
@dattran2k i think if using Firebase in open-source app is not secured

**Comment by d4f5409d** [comment]
You can use ACRA. It's what NewPipe uses.

**Comment by maxrave-dev** [comment]
Added ACRA in the latest release. Thanks @dattran2k @d4f5409d

**Comment by d4f5409d** [comment]
> Added ACRA in the latest release. Thanks @dattran2k @d4f5409d 

You're welcome
