### ISSUE TITLE
YT Music uploads not playing

### ISSUE THREAD

**Issue by JustQsa** [maxrave-dev/SimpMusic#190]
So, YT Music uploads are a feature i personally use a lot because of some artist whose songs arent on YT. They do get displayed on SimpMusic when i load a playlist, but whenever the songs are played only the name and author and even lyrics are loaded, but the song itself and duration isnt,

its also worth noting that the app displays at the bottom a Connection Timed Out error, my best guess is that this feature is meant to be used only by the user in question, and as the app technically counts as something else trying to access the content it just returns an error

**Comment by maxrave-dev** [comment]
May be private video issues
