### ISSUE TITLE
Some (most) downloaded songs do not play or stop right in the middle of playback.

### ISSUE THREAD

**Issue by Terkyz** [maxrave-dev/SimpMusic#191]
**Describe the bug**
When playing some downloaded songs, the song never starts because it stays at 0:00 or stops in the middle of playing with the error "Time out, check internet connection". In some songs this is fixed by choosing another song, but for most songs it does not.

**To Reproduce**
1. Download some songs
2. Play any song
3. Wait some time and maybe the song would never start, or it will stop playing exactly in the middle of the playback.

**Expected behavior**
It's a downloaded song, it should be play even without internet connection.

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by maxrave-dev** [comment]
#192 Thanks for your report. I will work with it

**Comment by maxrave-dev** [comment]
Can you remove cache and can it play?

**Comment by Terkyz** [comment]
I tried it and it doesn't seem to make much difference, as some songs that didn't even play before, now play but still stop after a few seconds, although the same "Time out, check internet connection" message is still displayed and the song doesn't play.

**Comment by Rcguen** [comment]
Soo has this error been fixed yet?

**Comment by maxrave-dev** [comment]
Sometimes data is corrupted by another reasons,, btw in latest build may be fixed
