### ISSUE TITLE
Error when going to artist page

### ISSUE THREAD

**Issue by OwenD30** [maxrave-dev/SimpMusic#194]
**Describe the bug**
When I click on any artist profile from any screen, instead of bringing up the artist page, it gives an error.

**To Reproduce**
1. Click on any artist from any screen

**Expected behavior**
App opens artist page with bio, top songs and albums

**Screenshots**
![Screenshot_20231221-173544](https://github.com/maxrave-dev/SimpMusic/assets/77121604/4858e519-7f3c-405c-8a1b-312415d28f71)

**Log (Error Details)**
N/A

**Comment by maxrave-dev** [comment]
Fixed in #184. Checkout Nightly Build in Actions
