### ISSUE TITLE
Showing more songs in playlist 

### ISSUE THREAD

**Issue by DeadSecTr** [maxrave-dev/SimpMusic#204]
![Screenshot_20231229-020416.png](https://github.com/maxrave-dev/SimpMusic/assets/90558189/54cf4866-2238-4cd5-a496-45c78f2b9539)

And there is no thumpnail in local Playlist

**Comment by misojournal** [comment]
You can change the thumbnail of the playlist yourself. You click on the 3 dots when you are on the playlist and you can change it.

**Comment by maxrave-dev** [comment]
Update to latest nightly build, back up it to YouTube Music, remove this local playlist and re-sync backed up to local, it will fix
