### ISSUE TITLE
Allow disable video

### ISSUE THREAD

**Issue by Sytten** [maxrave-dev/SimpMusic#209]
**Is your feature request related to a problem? Please describe.**
Currently some songs start with a video, on mobile data this is not ideal.

**Describe the solution you'd like**
Allow user to disable videos either all the time or for mobile data.

**Describe alternatives you've considered**
No clear alternative

**Additional context**
Thanks for the app it is awesome!

**Comment by maxrave-dev** [comment]
You can turn off playing video in Settings. Check it now

**Comment by Sytten** [comment]
Is it "play video if video track" to off? If so it is off when you install the app but it still plays videos. I think it work to toggle on/off.

**Comment by Sytten** [comment]
I really must not see something cause it still plays videos, probably there is another place but I just don't see it

**Comment by maxrave-dev** [comment]
Oh sorry for this bug. I design this in settings to turn off video, but unfortunately don't work. Will fix it
