### ISSUE TITLE
Allow ytm account selection

### ISSUE THREAD

**Issue by jioleight** [maxrave-dev/SimpMusic#210]
Add ability to switch account when ytm is logged in. Currently ytm defaults to main email address instead of the profile that was created ages ago in youtube.

**Comment by the-bose** [comment]
This has been the only issue that's stopping me from using the app as my primary music player.

**Comment by the-bose** [comment]
Genuinely the only feature that is missing from the app which would make it great for my use.

**Comment by maxrave-dev** [comment]
I will add this in the next version! Thanks for your recommend

**Comment by OwenD30** [comment]
It doesn't seem to be working on my end. It lets me add another account but it doesn't show up in the menu after I sign in and it doesn't sign into the account.

**Comment by jioleight** [comment]
> It doesn't seem to be working on my end. It lets me add another account but it doesn't show up in the menu after I sign in and it doesn't sign into the account.

You trying it on v0.1.7? Dev has implemented it in code but no builds released with it yet afaik.

**Comment by OwenD30** [comment]
> > It doesn't seem to be working on my end. It lets me add another account but it doesn't show up in the menu after I sign in and it doesn't sign into the account.
> 
> You trying it on v0.1.7? Dev has implemented it in code but no builds released with it yet afaik. 

I tried it on the nightly build code

**Comment by maribox** [comment]
@maxrave-dev 

I also think this did not fix the problem.
If you have multiple brand accounts it does
1. not sign in into the default Brand Accounts/channels and 
2. you can not switch the Brand Account/channel.

(If you want to experiment with the default Brand Account, go to Youtube -> Settings -> View Advanced Settings, there, if you have multiple Brand Accounts, you can set your default channel)

The only thing one can currently do that does have multiple Brand Account and the desired one that has all the Youtube History in it etc. is not the first in the list, is to delete all Brand Accounts that come before the first one in the list (which is oftentimes not the main one)

I am on  0.1.8, which is according to github the currently latest commit.

**Comment by maxrave-dev** [comment]
I tested on all of my own Google accounts. Worked. Why?![Screenshot_20240130-194517_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/5518dfbb-5ef2-48ec-a26d-cd9fcf37bd3d)
