### ISSUE TITLE
Songs that display Viewer discretion is advised. Do not play.

### ISSUE THREAD

**Issue by Aspect250** [maxrave-dev/SimpMusic#212]
**Describe the bug**
This song would normally have a popup(as seem in the first screenshot.) And if it isn't accepted (in normal yt music) the song won't load so maybe an auto accept it.

**To Reproduce**
1. Go to song Killing in the name of by rage against the machine
2. Try to play song
3. Song tries loading but cant giving(Time out. Check internet connection.

**Expected behavior**
Play song

**Screenshots**

1.Yt Music
![Screenshot_20240103_215338_ReVanced Extended Music.jpg](https://github.com/maxrave-dev/SimpMusic/assets/102602600/aaac6029-3cd8-4bf9-8a98-d2a096434bfa)

2. SimpMusic
![Screenshot_20240103_214901_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/102602600/1785a091-2bd8-4032-91b5-d4be91d4cd9d)

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by maxrave-dev** [comment]
Hmm, I tested in YT API. May be take a long time to research. Please be patient!

**Comment by Aspect250** [comment]
Installed debug apk and it works.![4e3cbf84-585c-4ac3-a114-06705460e891.jpeg](https://github.com/maxrave-dev/SimpMusic/assets/102602600/e52dfcce-2993-4ffb-bb99-b161cc8c5bb8)


Thanks for fixing it

**Comment by DarkCrypt** [comment]
@maxrave-dev 
This issue isn't fixed. Restricted songs don't play, v0.2.0.
