### ISSUE TITLE
Liked content

### ISSUE THREAD

**Issue by misojournal** [maxrave-dev/SimpMusic#213]
When we like a song or an album, the content liked isn't saved properly. Almost all the song liked are not saved in the liked songs playlist, just click on the like button is a bit difficult, I have to click numerus time on it to make it work but even after that the song isn't saved. For the album it's a bit different but the problem is the same, I 'don't have to click multiple time on the button but sometimes it's not saved.

**Comment by maxrave-dev** [comment]
This error was fixed in 0.1.8
