### ISSUE TITLE
Albums in Artist Page

### ISSUE THREAD

**Issue by dPandl** [maxrave-dev/SimpMusic#214]
**Is your feature request related to a problem? Please describe.**
If I'm looking for an artist and go to their profile, I would like to see all their albums at a glance and select them. 

**Describe the solution you'd like**
In the Artist page there should be a category with albums like in Spotify.

**Describe alternatives you've considered**
An alternative would be, for example, if I search Taylor Swift, all of her albums are displayed on the Albums tab, but it remains empty for me.  Maybe that's how it should be and it's a bug.

**Additional context**
![IMG_20240104_213226.jpg](https://github.com/maxrave-dev/SimpMusic/assets/35048273/46ae7e72-303f-49e7-a052-81c1657a2c4b)

![IMG_20240104_213147.jpg](https://github.com/maxrave-dev/SimpMusic/assets/35048273/5822238e-d43e-404f-8590-75f2e212fb0e)

**Comment by dPandl** [comment]
I just saw that no matter what i try to do I can't find any Albums in the App. So it is more likely a bug than i think.

**Comment by maxrave-dev** [comment]
Still work in my country. Try to use VPN

**Comment by dPandl** [comment]
I just found out that everything displays correctly when I'm not logged in with YouTube. When I'm logged in, albums don't appear even if I have a VPN on.
