### ISSUE TITLE
increase album tracks from 100

### ISSUE THREAD

**Issue by Einhander1** [maxrave-dev/SimpMusic#216]
There's been a few instances where an album I'm trying to listen to is cut off at 100 tracks where the album itself is beyond 100, I know it's few and far between but it is annoying.

Would you please kindly increase the number of tracks that can be played via an album from 100 to let's say 150.

This is not a high priority issue and I'm more concerned with bug fixes and crashes.

**Comment by maxrave-dev** [comment]
Which album bro? I need more information
