### ISSUE TITLE
Remove phone menu buttons

### ISSUE THREAD

**Issue by JonathanVanWin** [maxrave-dev/SimpMusic#217]
**Is your feature request related to a problem? Please describe.**
The android menu buttons are displayed and it doesn't look great. There is already the app menu so having also the android menu doesn't fit in.

**Describe the solution you'd like**
Hide it. Have it in Fullscreen mode.

**Comment by maxrave-dev** [comment]
Hi, please give me a screenshot

**Comment by JonathanVanWin** [comment]
![Screenshot_20240113-215059~2](https://github.com/maxrave-dev/SimpMusic/assets/36959015/192d69ba-0044-497a-8337-796f63b73e54)
It would be really great if it is possible to remove it. I think it is better, because Spotify doesn't have it and I see you are going for the Spotify look. Also the home search library buttons should be on a fade to black background from see through to black (I think you did that, but the android buttons are there, therefore the app buttons are without a background and looks weird).

It would be really great, and happy you answered so fast😊

**Comment by JonathanVanWin** [comment]
![Screenshot_20240113-220348](https://github.com/maxrave-dev/SimpMusic/assets/36959015/5cef9af5-787f-4791-a75e-a76f9441c987)
Added another example to show what I mean with the no background issue, I think the android buttons take it because I do see a black fade.

Add an example from Spotify, it is one of the screenshot in google play store: 
![Screenshot_20240113-220416](https://github.com/maxrave-dev/SimpMusic/assets/36959015/346bb11e-a716-4a9f-ac4a-b25a5130648a)
You can see the removed android buttons and black fade.

**Comment by maxrave-dev** [comment]
Ohhh, it caused by your "gesture settings" in your phone. Please dont use "3-button-gesture"
