### ISSUE TITLE
Artist name is not displayed from the share menu

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#218]
Every time you open a track from the share menu. The artist name is displayed as a number and letters.

See screenshot.

![Screenshot_20240112-230049_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/103368536/37b72ee6-638f-4c60-b40a-d8fe381e2754)

**Comment by maxrave-dev** [comment]
Sorry for this bug, wrong in my code
