### ISSUE TITLE
Discord sever 

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#22]
@maxrave-dev 
Hey man I'm a ex moderator of many github  projects and also the main dev of redbot discord bot I was thinking can I make you a discord sever for this project this opens up a Community for people to report bugs and ask for new features obviously I can keep track on the issues they open and remove any duplicate ones we can also upload bigger files like screen records that github can't do.

Many thanks 😊

**Comment by maxrave-dev** [comment]
Thanks bro, you can do it

**Comment by owencz1998** [comment]
Thanks dude 😁😁

**Comment by owencz1998** [comment]
https://discord.gg/Rq5tWVM9Hg
