### ISSUE TITLE
Adding and Removing Songs within Account Playlists

### ISSUE THREAD

**Issue by ArpitSaini00** [maxrave-dev/SimpMusic#224]
Thank you so much for this YTM client, this is the best open source client available on the internet.
I have feature suggestion. As we are already able to view and download youtube music account playlists. It'd be great if we are able to directly add and remove items within them. (If it helps, SpMp has this feature)

**Comment by ArpitSaini00** [comment]
I know local playlists are synced to youtube account but the order of songs when u download any youtube playlist changes. Thus, it'd be great if we can directly add or remove within the youtube playlist

**Comment by maxrave-dev** [comment]
In the latest nightly version, when the first synced, the order of songs is same with online playlist. Check it!

**Comment by ArpitSaini00** [comment]
This is perfect! Thank you so much 😁

**Comment by DeadSecTr** [comment]
> In the latest nightly version, when the first synced, the order of songs is same with online playlist. Check it!

Where can i find it?

**Comment by ArpitSaini00** [comment]
> > In the latest nightly version, when the first synced, the order of songs is same with online playlist. Check it!
> 
> Where can i find it?

You can fork this repository and build the latest nightly using workflow

**Comment by maxrave-dev** [comment]
> > In the latest nightly version, when the first synced, the order of songs is same with online playlist. Check it!
> 
> Where can i find it?

https://github.com/maxrave-dev/SimpMusic/actions/
