### ISSUE TITLE
It shows "error" when i click on "popular" section of artist

### ISSUE THREAD

**Issue by dainvincible1** [maxrave-dev/SimpMusic#23]
![image](https://github.com/maxrave-dev/SimpMusic/assets/127825700/d2553c7f-e27a-459c-b502-506d128f4089)

**Comment by maxrave-dev** [comment]
What screen did you open before you open artist screen?

**Comment by dainvincible1** [comment]
> What screen did you open before you open artist screen?

I opened the search bar then searched "the weeknd"

**Comment by maxrave-dev** [comment]
Some time server response not full data. Retry again.

**Comment by dainvincible1** [comment]
> Some time server response not full data. Retry again.

yeah its working now. thanks
