### ISSUE TITLE
Using the OPUS codec

### ISSUE THREAD

**Issue by hachikoharuno** [maxrave-dev/SimpMusic#233]
Hello, I looked at the issue related to sound quality. As I understand it, the bitrate limitation is associated with the use of the m4a codec (container), however, when using the OPUS (youtube music revanced) codec, even without youtube premium the bitrate is displayed as 251.

The first support appeared in version v2.181.1 of the patch from inotia00.
#https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1

I don't understand technical implementation so I would like to know if it is possible to implement a similar function in your application?

**Comment by maxrave-dev** [comment]
hmmm, 251 is itag, and current maximum SimpMusic quality is 129kps with 251 itag and codec is opus, mimetype is webm

**Comment by hachikoharuno** [comment]
Yes, you are right, I did not understand the topic.

**Comment by bt4ibwem8** [comment]
Does app automatically choose the highest bitrate for streaming? Is it currently opus 160 kbps?
