### ISSUE TITLE
Songs, not videos in all playlists

### ISSUE THREAD

**Issue by Johndjk** [maxrave-dev/SimpMusic#239]
I don't know if it's a technical limitation since all the apps I've tested that use the Youtube API only show videos in playlists.

The only one that actually shows songs is https://github.com/KRTirtho/spotube, but it uses Spotify's API.

But if it's possible to show only songs, it would be wonderful, because even being able to skip the segments doesn't make it a good experience.

**Comment by maxrave-dev** [comment]
Turn off playing video in settings please!

**Comment by Johndjk** [comment]
I already use it disabled, however, I refer that all playlists could be the same as the community playlists with the songs and covers from Youtube Music. It's easier to identify songs and more visually pleasing.

![community playlists](https://github.com/maxrave-dev/SimpMusic/assets/154085819/bb938368-3769-49ec-8a9b-bb69f5bf6c54)

![others playlits](https://github.com/maxrave-dev/SimpMusic/assets/154085819/a3dce426-ee2a-44c9-8c6a-f513873a3ce6)

**Comment by maxrave-dev** [comment]
![image](https://github.com/maxrave-dev/SimpMusic/assets/113747128/d759e36c-7dbc-4b8a-b92a-e231bbfe6379)
As you see, YouTube Music Featured Playlist contains video only

**Comment by Johndjk** [comment]
Songs on playlists like Spotify are discarded then?

I would really love that, because in videos it usually has effects, noises and so on, which detract from the user experience.
