### ISSUE TITLE
Generate nightly versions via Actions

### ISSUE THREAD

**Issue by airon90** [maxrave-dev/SimpMusic#24]
As you can see [here](https://github.com/z-huang/InnerTune/actions) you can generate nightly version of that app after every PR. It can help you in finding and solving bugs

**Comment by maxrave-dev** [comment]
Thanks so much. I haven't known this before. I will check it

**Comment by airon90** [comment]
It seems that it is not working

**Comment by airon90** [comment]
@maxrave-dev It seems that it doesn't work as it doesn't generate any file

**Comment by kairusds** [comment]
@maxrave-dev The builds produced by the workflow doesn't give an installable apk file.
