### ISSUE TITLE
more lyrics api

### ISSUE THREAD

**Issue by user12xxxxxx** [maxrave-dev/SimpMusic#242]
Problem
Musixmatch and yt doesn't have many lyrics

Solution (i think this might work)
More lyrics search api

![Screenshot_20240204-205558](https://github.com/maxrave-dev/SimpMusic/assets/111512589/b5b7f917-93b5-4bb6-b55d-62388b1734e9)
![Screenshot_20240204-210404](https://github.com/maxrave-dev/SimpMusic/assets/111512589/d961d3b8-5455-4cec-b391-30e871863804)
![Screenshot_20240204-210410](https://github.com/maxrave-dev/SimpMusic/assets/111512589/dc8844fd-0629-46b9-ba0d-43b3e02bca56)

**Comment by user12xxxxxx** [comment]
what about spotify lyric api
https://github.com/akashrchandran/spotify-lyrics-api

**Comment by maxrave-dev** [comment]
Sorry but Spotify is using only Musixmatch

**Comment by user12xxxxxx** [comment]
But Spotify app has lyrics 
![Screenshot_20240205-122548](https://github.com/maxrave-dev/SimpMusic/assets/111512589/e80010e5-4f72-42ca-828c-ca9c8e35893b)
![Screenshot_20240205-122440](https://github.com/maxrave-dev/SimpMusic/assets/111512589/3834f852-80a3-484b-b683-54bd2fcd8c38)
Also  spotube, it fetches data from Spotify 
![Screenshot_20240205-111408](https://github.com/maxrave-dev/SimpMusic/assets/111512589/431d81c3-6146-4611-b3b7-d4fd6ba7c0f3)

**Comment by maxrave-dev** [comment]
If I use Spotify for lyrics, need to log in to Spotify account. Is it comfortable? Do you know any public API to get India Lyrics?

**Comment by user12xxxxxx** [comment]
Yeah makes sense many may not wanna (but you can keep it optional for those who want?)
I don't know much lyrics api but genius lyrics api seems good (what do think?)
Also these are few foss apps I use for lyrics
https://github.com/illusionman1212/lyrics-grabbr
https://github.com/Lambada10/SongSync
Do let me know

**Comment by maxrave-dev** [comment]
I don't want to use Spotify, I used before.

**Comment by user12xxxxxx** [comment]
> I don't want to use Spotify, I used before.

ok
what about genius api

**Comment by maxrave-dev** [comment]
NO, may be I will implement Spotify again 😂😂😂

**Comment by user12xxxxxx** [comment]
Okay that will work to

**Comment by user12xxxxxx** [comment]
Thanks
