### ISSUE TITLE
Make Initial Loading Faster

### ISSUE THREAD

**Issue by anxiouslelimo** [maxrave-dev/SimpMusic#245]
**Is your feature request related to a problem? Please describe.**
Streaming/initial loading is slow compared to players like Innertune which also used innertube api

**Describe the solution you'd like**
Faster streaming/loading of songs

**Comment by maxrave-dev** [comment]
Try latest debug version in Actions tab

**Comment by maxrave-dev** [comment]
Wait for release version. Because debug always slower than release
