### ISSUE TITLE
Unexpected Changes in UI

### ISSUE THREAD

**Issue by albinxshiby** [maxrave-dev/SimpMusic#246]
**Describe the bug**
I've attached an image, after playing some songs or changing some artists, the blurry color difference happens. 
It's not a big issue but I'm just reporting it

**To Reproduce**
1. It happens after sometime playing, changing and doing some stuffs.

**Device Details**
Realme 9 pro
Motorola edge 

**Screenshots**
![IMG_20240207_213311.jpg](https://github.com/maxrave-dev/SimpMusic/assets/145864271/b9d9d25f-badb-46c4-b163-f6d4ce749ca6)

**Log (Error Details) skipped**

**Comment by maxrave-dev** [comment]
I dont understand your question. Because this image look like normal

**Comment by albinxshiby** [comment]
> I dont understand your question. Because this image look like normal

Sorry about this
It's a mistake
