### ISSUE TITLE
Package conflicts

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#253]
For the debug version not sure about the full release but could this be fixed so I don't have to keep deleting the app and installing the new one please.

![Screenshot_20240213_061732_Package installer.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/de8ab808-5365-45d8-8d08-1fd2a4ed3f3a)

**Comment by maxrave-dev** [comment]
Sorry but I still use parallel debug and release
![Screenshot_2024-02-13-22-29-25-377_com.miui.securitycenter.jpg](https://github.com/maxrave-dev/SimpMusic/assets/113747128/a6f2e3fa-8c9a-4ed4-a064-555185f6992b)

**Comment by maxrave-dev** [comment]
If cant install, you can back up data and restore

**Comment by owencz1998** [comment]
No worries just thought there was away to fix lol
