### ISSUE TITLE
Search button doesn't work

### ISSUE THREAD

**Issue by andreatede2002** [maxrave-dev/SimpMusic#256]
Search button doesn't work

https://github.com/maxrave-dev/SimpMusic/assets/62845064/fbad6943-22e8-4a65-be4a-d510b4cd1382

**Comment by maxrave-dev** [comment]
remove app and reinstall, i dont have this bug

**Comment by andreatede2002** [comment]
> remove app and reinstall, i dont have this bug

Removed and reinstalled but I still bave this issue. V0. 1.8

**Comment by maxrave-dev** [comment]
This error caused by your phone

**Comment by maxrave-dev** [comment]
Try to install a new ROM
