### ISSUE TITLE
App cannot remove the song from "YouTube Liked"

### ISSUE THREAD

**Issue by bkrucarci** [maxrave-dev/SimpMusic#259]
**Describe the bug**
We have a new feature "Add to YouTube Liked". I can add musics to youtube liked section but I cannot remove it from the list.
I clicked the little button at bottom but button stay still as "check" icon. The pop up says "Removed from list" but the song still stay in the list. Please check it.

**To Reproduce**
1. Go to the song
2. Touch the "Add to YouTube Liked" button at bottom of the player
3. Song added to the list
4. Then touch the "check" icon to remove song from the list
5. pop up appears and says "Removed from the list"
6. Song stay still at the list 

**Expected behavior**
Song should be removed from the list after touching the remove icon.

**Comment by maxrave-dev** [comment]
For me, it removed, check out your internet, not a bug

**Comment by maxrave-dev** [comment]
#260
