### ISSUE TITLE
[Feature Request] Remove "YouTube Liked List" Option

### ISSUE THREAD

**Issue by bkrucarci** [maxrave-dev/SimpMusic#260]
**Is your feature request related to a problem? Please describe.**
https://github.com/maxrave-dev/SimpMusic/issues/259

**Describe the solution you'd like**
Add an option to batch process of the songs in the lists. Keep touching on song and preferences should appear.
I have to open the song to remove song from the "YouTube Liked" list (the new feature 0.2.0)

Please add an option shown below. Thanks

**Additional context**
![JEWzSDl](https://github.com/maxrave-dev/SimpMusic/assets/15933805/f7fdd3da-1006-4d29-ae85-7ed8a7528534)

**Comment by maxrave-dev** [comment]
https://github.com/maxrave-dev/SimpMusic/assets/113747128/50124aee-129a-46f4-a8fa-39831f5d9808

**Comment by bkrucarci** [comment]
@maxrave-dev Dear developer, it is also a feature request not only bug report. Please consider to select multiple songs to make action. Thanks.
