### ISSUE TITLE
Lyrics texet

### ISSUE THREAD

**Issue by Ekki2015** [maxrave-dev/SimpMusic#262]
**Describe the bug**
The lyrics card is overlapping the artist image in Spotify Canvas

**Expected behavior**
It would be nice when you tapp on the screen it should appear.

https://github.com/maxrave-dev/SimpMusic/assets/12226562/9edbf808-f415-4211-a3a6-2231e1374927

**Comment by maxrave-dev** [comment]
try to decrease dpi below 432
