### ISSUE TITLE
Three-point menu repositioned

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#263]
Please place the three-dot menu next to the like button this would make it a little easier to use. See screenshot.

![Screenshot_20240217-170224_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/103368536/293b720e-1810-44db-841f-af9b716b0cc1)

**Comment by maxrave-dev** [comment]
Spotify doesn't do it, YT Music doesn't do it, so I don't
