### ISSUE TITLE
Add entire playlist to the current playback

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#264]
It would be cool to have a function that allows you to add an entire playlist to the current playback with a plus sign or similar or via the three-dot menu.

![Screenshot_20240217-200649_SimpMusic_1](https://github.com/maxrave-dev/SimpMusic/assets/103368536/8b3c5365-5318-4249-bba4-8f187ebcba76)

**Comment by siggi1984** [comment]
Thanks bro.

**Comment by maxrave-dev** [comment]
@siggi1984 Check out latest nightly ver
