### ISSUE TITLE
[Feature request] Shuffle and repeat buttons

### ISSUE THREAD

**Issue by hussainalhaddad** [maxrave-dev/SimpMusic#266]
Hi

Is it possible to add shuffle and repeat support on Android Auto?

Thank you.

**Comment by maxrave-dev** [comment]
Repeat supported in Android Auto
![image](https://github.com/maxrave-dev/SimpMusic/assets/113747128/a3e89117-8aaf-44f0-83b1-a2710b9f4c53)

**Comment by hussainalhaddad** [comment]
Strange! It doesn't show up in my car!!

Honda Accord 2021

**Comment by zachvlat** [comment]
Any plans to include shuffle for AA, also?
