### ISSUE TITLE
Random next song if popolar song from an artist is played

### ISSUE THREAD

**Issue by memor27** [maxrave-dev/SimpMusic#267]
**Describe the bug**
If you select song from Popolar song tab in Artist, the next song in queue is a random one, most of the time not related to the artist but more likely to what I've listened in the past.

**To Reproduce**
1. Go to 'Artist Name'
2. Click on 'One song in Popular Tab'
3. Press "next song button"
4. A random song is played

**Expected behavior**
When you press "next song" it should play the next song you see in the popular song list

**Screenshots**
https://github.com/maxrave-dev/SimpMusic/assets/100342106/08807a03-0d87-4561-ad49-267d128857b3

**Comment by maxrave-dev** [comment]
Click to show full popular songs to play all songs of this artist.
