### ISSUE TITLE
Import from Innertune

### ISSUE THREAD

**Issue by airon90** [maxrave-dev/SimpMusic#27]
Can you support import backup from [Innertune](https://github.com/z-huang/InnerTune)?

**Comment by maxrave-dev** [comment]
NO, because SimpMusic's database is different from InnerTune

**Comment by airon90** [comment]
So I can't move from Innertune and I have to import 5k+ songs in SimpMusic, am I right?

**Comment by maxrave-dev** [comment]
So hard to do this 😥😥😥

**Comment by SYCOINFERNO** [comment]
so is it possible?
to do that if so can u tell me how i have tried to change the .db file after extracting the .backup and changing the name of the Music Database
but no luck
