### ISSUE TITLE
App display is too big and the play button is at the bottom

### ISSUE THREAD

**Issue by zerobun** [maxrave-dev/SimpMusic#270]
**Describe the bug**

The display of the app is quite big and that causes the app have unnecessary spaces in between things and that in turn causes things to be much further away then they should be. 

**To Reproduce**

Might be caused by phone, using vivo y11 android 11

**Expected behavior**

To atleast not have to be scrolling down to click play/pause. 

**Screenshots**

![Screenshot_20240219_015725](https://github.com/maxrave-dev/SimpMusic/assets/127630316/b6078cf3-783c-4d96-b976-967ab5001b43)

It's clear in the ss that there's lots of unused spaces around the album art, and it's causing the music control buttons to be pushed under the phone navigation buttons (or so I think). 

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by maxrave-dev** [comment]
For fixing, try to increase dpi to 410 - 432

**Comment by maxrave-dev** [comment]
Yes, I will make it in next build
