### ISSUE TITLE
Playlist starts at the bottom.

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#272]
Not sure if this is because I've selected the filter to show newly added songs at the top.

But when I open the playlist, it starts at the bottom, which is pretty annoying.

Ask me on Discord if you don't understand, as I can't upload a video due to GitHub's limit on video size.

![Screenshot_20240219_084252_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/ce770ddf-bada-4981-99a8-d4ba90b6a2a5)

**Comment by maxrave-dev** [comment]
#273
