### ISSUE TITLE
Next song to play issues

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#273]
When using the filter for new songs to be at the top, it also sees them as the last song on the playlist. As you can see, the song I'm listening to is at the top, but in the second screenshot, you can't click "next" to play the song underneath.

![Screenshot_20240219_083925_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/0e5f2b63-2195-4919-930d-be42c1e1b265)

![Screenshot_20240219_083934_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/f3c307b8-caf3-4fd3-8f0b-40fdc8a0a5af)

**Comment by maxrave-dev** [comment]
I combine 2 issues to one

**Comment by owencz1998** [comment]
No worries brother 😀
