### ISSUE TITLE
Two important problems, and five suggestions

### ISSUE THREAD

**Issue by eliasoft** [maxrave-dev/SimpMusic#275]
Hello dev. Thank you for developing this app.
After having tested several similar apps, I settled on SimpMusic. But there are two issues that you need to solve as soon as possible.

___
# Issue 1.
When downloading a playlist, the covers of the downloaded songs should also be downloaded, and these in turn should not be stored in the cache directory. Two ways to implement this: embed the images within the audio files, or store the image files by assigning them the same name as the corresponding audio files.

___
# Issue 2 (optimization).
Open a playlist containing at least 100 songs (either downloaded or not downloaded). Start playing from the first song, and then repeatedly press the button to go to the next song until you reach the last song in that list. You will notice that as you progress, the user interface becomes slower progressively.
In case you don't notice this problem, I must tell you that I have a low-end phone, but even so, this does not happen to me with the official *YT Music* app, nor with only local players such as *Musicolet* and *Poweramp*.

___
## Five suggestions that are easy to implement and that I am sure will be pleasant for all users of this app.
1. Possibility to establish that when you start the app, the library is displayed instead of the home screen.
2. Ability to establish that downloaded playlists to be located at the top of the library. exactly above the colored rectangles.
3. Ability to establish that downloaded playlists to be viewed as a list instead of grid.
4. I want to change the sort order of the list of downloaded playlists.
5. The title of each downloaded playlist should not include the name of the creator, much less the word "Downloaded".

**Comment by maxrave-dev** [comment]
Thanks for suggest, I will review

**Comment by Jester-B** [comment]
the downloaded playlist can be deleted ?

**Comment by CrazyWolf13** [comment]
Duplicates of the following:

Issue 1: [https://github.com/maxrave-dev/SimpMusic/issues/848](https://github.com/maxrave-dev/SimpMusic/issues/848)

Issue 2: [https://github.com/maxrave-dev/SimpMusic/issues/816](https://github.com/maxrave-dev/SimpMusic/issues/816)

Feat 1: [https://github.com/maxrave-dev/SimpMusic/issues/353](https://github.com/maxrave-dev/SimpMusic/issues/353)

Feat 2: [https://github.com/maxrave-dev/SimpMusic/issues/353](https://github.com/maxrave-dev/SimpMusic/issues/353)

Feat 3: [https://github.com/maxrave-dev/SimpMusic/issues/353](https://github.com/maxrave-dev/SimpMusic/issues/353)

Feat 4: [https://github.com/maxrave-dev/SimpMusic/issues/931](https://github.com/maxrave-dev/SimpMusic/issues/931)

Feat 5: [https://github.com/maxrave-dev/SimpMusic/issues/848](https://github.com/maxrave-dev/SimpMusic/issues/848)
