### ISSUE TITLE
Support for Spotify Playlists

### ISSUE THREAD

**Issue by karmakarmeghdip** [maxrave-dev/SimpMusic#277]
**Is your feature request related to a problem? Please describe.**
Spotify Playlists are publicly available and many people share their Spotify Playlists, so support for it would be helpful.

**Describe the solution you'd like**
A way to import Spotify Playlist from a URL by pasting it into the app

**Comment by Geigerkind** [comment]
If you sync with your youtube account, you can use this tool:
https://github.com/linsomniac/spotify_to_ytmusic

or tunemymusic.com

Both work like a charm, though the latter is restricted to 500 songs per playlist.

**Comment by maxrave-dev** [comment]
Use this https://github.com/sigma67/spotify_to_ytmusic
