### ISSUE TITLE
Play only tracks from the chosen artist in the random option on the artist page, not similar

### ISSUE THREAD

**Issue by Johndjk** [maxrave-dev/SimpMusic#281]

**Comment by maxrave-dev** [comment]
Please click more in Songs of Artist !!!

**Comment by Johndjk** [comment]
I'm just saying that in the app you don't have an option to listen to random songs from the same artist (which should be at least by clicking on one of the popular songs on the artist's page).

Only play similar songs in the auto queue.

I miss this option because on Spotify they are songs by the same artist in the automatic queue.

**Comment by maxrave-dev** [comment]
You can open the Artist's songs playlist, then click shuffle button

**Comment by Johndjk** [comment]
Oh, my god! I'm sorry I didn't notice this option.
As I don't speak English fluently, I didn't understand your description of how to get the random songs.
Only now using the app did I find out and remember what you had said here.
Sorry, really!
Thank you for your work and attention!
