### ISSUE TITLE
Please add Arabic language

### ISSUE THREAD

**Issue by amribrahim1** [maxrave-dev/SimpMusic#283]
Your app is really amazing, thank you.

I want to suggest to:

1. Add Arabic language to the language list, please.
2. Add "download" option to the menu of the song from playlist screen, 
![صورة واتساب بتاريخ 1445-08-15 في 10 04 31_6c8273bd](https://github.com/maxrave-dev/SimpMusic/assets/8148579/49304aa6-1f22-4e4c-8048-5d30dd5560b1)

Thanks.

**Comment by maxrave-dev** [comment]
Contribute your language to Crowdin. Please read README FIRST 🙏

**Comment by amribrahim1** [comment]
Ok, I will do that, what about my second suggestion? 😁

**Comment by amribrahim1** [comment]
Ok, I will do that, what about second suggestion? 😁
