### ISSUE TITLE
No albums section on artists pages

### ISSUE THREAD

**Issue by Info-BC** [maxrave-dev/SimpMusic#285]
Hello, I'm logged in with Google account, french language, when I go on any artist page, I don't see the albums section. I have "popular tracks" and then "videos". the "albums" section should be between those two.

v0.2.0 on Android 13

**Comment by Info-BC** [comment]
Another thing, if I press the 3 dots at the right of a track, it shows "no album" in the menu so I can't reach an album this way too.

**Comment by maxrave-dev** [comment]
![Screenshot_20240301-195021_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/b4afe5cf-e627-4e2b-a494-c04ba68b3b16)

![Screenshot_20240301-195002_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/07319e5c-d60d-4c8c-b171-ab7c8314527f)

French language, still work normal. 
And some song dont have album okay?

**Comment by Info-BC** [comment]
If I use the app on guest not logged in with google account, I see the "singles" and "albums" section of an artist. But if I'm logged in, these sections are missing.

Guest :
![guest](https://github.com/maxrave-dev/SimpMusic/assets/92523501/b7d043de-b0f8-4aac-9c16-a7fd86110570)

Logged :
![logged](https://github.com/maxrave-dev/SimpMusic/assets/92523501/7d9d37b0-9d98-4757-b5a7-79b88f7feee2)

Another thing, logged or not it's the same, on an artist page, popular tracks section if I press the 3 dots I can see and access the album :

![artist](https://github.com/maxrave-dev/SimpMusic/assets/92523501/47a43a95-83a5-4022-9e6b-c6b65df070c6)

But if I go to the popular track pages to see more tracks, then it's "no album":

![popular](https://github.com/maxrave-dev/SimpMusic/assets/92523501/cd277ad6-17af-462a-aecf-6fdbb328b4cd)

**Comment by maxrave-dev** [comment]
Did you try to change your account?

**Comment by maxrave-dev** [comment]
![image](https://github.com/maxrave-dev/SimpMusic/assets/113747128/0ce72db1-8bc9-4b8a-a9b6-9ab62dda1ada)
