### ISSUE TITLE
Support Matrix additional to Discord

### ISSUE THREAD

**Issue by JokerGermany** [maxrave-dev/SimpMusic#287]
Would be great if you would let the user the choice if the want to use a free or proprietary chat protocol and support Matrix ( element.io ), too.

Would be cool if you you would bridge your discord Server with Matrix
https://t2bot.io/discord/

**Comment by owencz1998** [comment]
I'm able to do this but what is the advantage @JokerGermany

**Comment by JokerGermany** [comment]
The advantage is to give the people a freedom of choice.
I don't want to use discord.

I want to use a free, open protocol without something unknown controlling something.
https://www.youtube.com/watch?v=uvNkdAggUGU

**Comment by owencz1998** [comment]
Oh like using element app @JokerGermany

**Comment by owencz1998** [comment]
![Screenshot_20240228_205154_Element.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/0c4d5d4f-e95a-40d1-a975-35be616b43a6)

**Comment by owencz1998** [comment]
Having issues

**Comment by JokerGermany** [comment]
you need to open discord in an browser and copy the server adress from the url
If you need help regarding bridging and matrix (and moderation of matrix) you can write me @jokergermany:matrix.org

**Comment by JokerGermany** [comment]
e.g. the general chat has this url:
https://discord.com/channels/1136988323819298856/1136993566074351668

=> Means: `!discord bridge 1136988323819298856 1136993566074351668`

**Comment by JokerGermany** [comment]
If you give me your matrix id, i can create the spaces and rooms and then make you admin in this rooms if you want.

**Comment by owencz1998** [comment]
https://matrix.to/#/#simpmusicdiscord:matrix.org

**Comment by maxrave-dev** [comment]
Sorry, but I don't understand. Anyone explain for me plz 🥹🥹🥹

**Comment by JokerGermany** [comment]
Give me a break, I will help you in approximately 1 hour

**Comment by owencz1998** [comment]
> Sorry, but I don't understand. Anyone explain for me plz 🥹🥹🥹

So people can message using other apps instead of just discord but we will see the message in discord and cross other apps

**Comment by JokerGermany** [comment]
> Sorry, but I don't understand. Anyone explain for me plz 🥹🥹🥹

Matrix is an open, decentral alternative to discord.
When you Bridge Discord Channels to Matrix Rooms both sides can talk with each other.

general chat from Discord perspective:
![grafik](https://github.com/maxrave-dev/SimpMusic/assets/30293477/c179e04d-5b84-4f5e-8d3e-12a6954b5cc1)

general chat from Matrix perspective:
![grafik](https://github.com/maxrave-dev/SimpMusic/assets/30293477/ef622dbe-229c-444f-928e-e0f20594ae27)

**Comment by owencz1998** [comment]
So anyone can edit or delete the channels which would be bad to add anyone as moderation

**Comment by JokerGermany** [comment]
e.g. i can't do anything in your created room https://matrix.to/#/#simpmusicdiscord:matrix.org

**Comment by JokerGermany** [comment]
Until now only one channel is bridged.

**Comment by owencz1998** [comment]
I will sort this out tomorrow
