### ISSUE TITLE
[family link] Google Account not added

### ISSUE THREAD

**Issue by JokerGermany** [maxrave-dev/SimpMusic#289]
**Describe the bug**
Family link is a way to supervise your kids.
When you login with an family link account you get the message that the login was successful, but the Account is isn't added to SimpMusic.

**To Reproduce**
1. Create a supervised family account
2. Try to login with this Account
3. You will get the Message from SimpMusic that the Login was successful, but it wasn't added.

**Additional In formations**
It doesn't matter if you set up in family link that the account can log in on itself or if a parent has to confirm it.
![simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/30293477/56a10caa-039a-4ed1-bef6-98e7e6267dd2)

**Comment by JokerGermany** [comment]
I think the Bug isn't family link.
I will make a new Bug report

**Comment by JokerGermany** [comment]
> Please use a normal account 🥺🥺🥺

no

**Comment by maxrave-dev** [comment]
Hey bro, I read this again and please confirmed by parents. I don't or plan any feature to bypass this

**Comment by JokerGermany** [comment]
It's not about bypassing it.
I am somewhat like the parent ;)
I have with this account the problems like discribed in #290 (Screenshot in the issue is from there is his family link account)
I thought it's not because family link, but because he has no youtube channel but you said it works even without youtube channel for you.
