### ISSUE TITLE
Use in Google Assistant

### ISSUE THREAD

**Issue by JokerGermany** [maxrave-dev/SimpMusic#291]
Would be nice if there would be a way using simpMusic in Google Assistant.
Are only Google Play Apps supported in Google Assistant?

![Screenshot_20240229-105314](https://github.com/maxrave-dev/SimpMusic/assets/30293477/cb540b18-11b7-49fb-ac95-cdb442a84267)

**Comment by maxrave-dev** [comment]
I tried but docs is not helpful. So wait for Gemini App replaced GG Assistant

**Comment by maxrave-dev** [comment]
https://github.com/androidx/media/issues/762
Follow this, GG Assistant only supports apps which downloaded from GG Play Store
