### ISSUE TITLE
Can't add to playlist

### ISSUE THREAD

**Issue by rabaimorp** [maxrave-dev/SimpMusic#293]
(device info)
Device: Samsung Galaxy a53
Android version: 14
Custom ROM: Lineageos 21 (light, degoogled, with magisk)
Custom Kernel: 5.10.136-afaneh92-gc7f4d0fa021e

Issue: The "add to playlist" doesnt work, just shades the screen until I cancel (screenshot)
![Screenshot_20240229-153043_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/161316025/71af919e-bc87-4cc0-80f5-294701f37466)

**Comment by maxrave-dev** [comment]
Do you have any local playlist?

**Comment by rabaimorp** [comment]
> Do you have any local playlist?

No, I have playlists in youtube music. (Im logged in with a youtube account). There is an option to listen to my online playlists, so I assumed I can also add music to them in the app

**Comment by owencz1998** [comment]
Make it local playlist and then turn on sync
