### ISSUE TITLE
App does not comply with Google's use secure browsers policy when trying to log in to Spotify with Google

### ISSUE THREAD

**Issue by Zeitiah** [maxrave-dev/SimpMusic#297]
**Describe the bug**
When I tried (multiple times) to log in to Spotify with Google in the app. I get an error stating that Google will not let me in because the app does not comply with the use sevure brpwsers policy. 

Here is the text: 
Spotify’s request does not comply with Google’s ”Use secure browsers” policy. If this app has a website, you can open a web browser and try signing in from there. If you are attempting to access a wireless network, please follow [these instructions](https://support.google.com/accounts/answer/9690282).
You can also contact the [developer](https://accounts.google.com/) to let them know their app must comply with Google’s ”Use secure browsers” policy.
[Learn more about this error](https://support.google.com/accounts/answer/7675428)
If you are a developer of Spotify, see [error details](https://accounts.google.com/).
Error 403: disallowed_useragent

**To Reproduce**
1. Tap the login to Spotify button
2. Try to sign in with Google
3. See error

**Comment by maxrave-dev** [comment]
Try to update your webview or change default webview to Chrome
