### ISSUE TITLE
Audio playing animation keeps running when the song is paused in Library Fragment

### ISSUE THREAD

**Issue by wicked111** [maxrave-dev/SimpMusic#298]
**Describe the bug**
Audio playing animation keeps running when you pause the player in Library Fragment

**To Reproduce**

1.  Play any song in the Home fragment.
2.  Now go to Library fragment -> Recently Added, you'll see the animation is running in the place of thumbnail of the currently playing song.
3.  Now pause the Song from the player.
5.  Animation isn't stopped and indicating that the current track is still playing...which is not a good practice in music apps.

**Expected behavior**
I expected that when you pause the song the animation visibility should be gone and the thumbnail visibility will be restored...., and we can apply any other logo to showcase that the currently played track of the player is paused.

Admins can assign me this issue so that I can work on it.

**Comment by maxrave-dev** [comment]
Thanks, I will fix
