### ISSUE TITLE
the app crashes frequently

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#3]
the app crashes frequently, mostly in the settings menu. if you e.g. clicks Downloads or most played.

Device: Samsung Galaxy a8, Android 9

**Comment by maxrave-dev** [comment]
Can you send me crash logs? Which version did you use? From Github or IzzyOnDroid?

**Comment by siggi1984** [comment]
> Can you send me crash logs? Which version did you use? From Github or IzzyOnDroid?

I have the one from izzyondroid, I'll try the version from github.

**Comment by maxrave-dev** [comment]
Could you give me more crash logs to know your issue? I test in my phone and some emulator and download feature is working perfectly

**Comment by siggi1984** [comment]
> Could you give me more crash logs to know your issue? I test in my phone and some emulator and download feature is working perfectly

with the apk from github the app also crashes occasionally

Unfortunately I don't know how to get a crash report from the app

**Comment by maxrave-dev** [comment]
Did you know how to use ADB? Please connect your device to your PC and run ADB with this command:
`adb logcat --buffer=crash `

**Comment by siggi1984** [comment]
okay, I'll see if I can fix it, otherwise I'll wait for the next version, maybe that will fix it.
