### ISSUE TITLE
Can't log out only from my Spotify account.

### ISSUE THREAD

**Issue by FaqatZubair1** [maxrave-dev/SimpMusic#303]
**Is your feature request related to a problem? Please describe.**
If I want to log out just from my Spotify account, it asks log out from YouTube too.

**Comment by maxrave-dev** [comment]
Oh I see, this is a bug

**Comment by FaqatZubair1** [comment]
Hey!
I'm unable to look for debug version of this app. The nightly builds doesn't open. What to do?

**Comment by maxrave-dev** [comment]
Check this: https://nightly.link/maxrave-dev/SimpMusic/workflows/android/dev/app.zip

**Comment by FaqatZubair1** [comment]
Just to be honest, the debug app has more bugs than normal one.
