### ISSUE TITLE
Music stays in the notification

### ISSUE THREAD

**Issue by FaqatZubair1** [maxrave-dev/SimpMusic#308]
**Describe the bug**
If we pause the song and then close the app, the song still remains in the notifications, and we can't remove it.
If we close the app while the song is playing, it is also removed from the notifications

**Expected behavior**
The song should get removed from the notifications in both the cases .

**Comment by FaqatZubair1** [comment]
https://github.com/maxrave-dev/SimpMusic/assets/161596117/dee52fac-4fb9-48d9-951a-aa6868008503
This will help you understand the issue better

**Comment by maxrave-dev** [comment]
![Screenshot_20240312-074634_Settings.png](https://github.com/maxrave-dev/SimpMusic/assets/113747128/3ffdcbfe-5361-4d48-ae39-1415d6d8d085)

Turn off this

**Comment by FaqatZubair1** [comment]
I have already done this, the issue still remains
