### ISSUE TITLE
Scaling issues in player menu

### ISSUE THREAD

**Issue by d4f5409d** [maxrave-dev/SimpMusic#31]
We have to scroll down to see the buttons in the bottom at the player screen.
![Screenshot_2023-08-08-21-20-23-07_b4450e33c7076f102e79bbedaff38911.jpg](https://github.com/maxrave-dev/SimpMusic/assets/76624594/3f7a0f7a-d671-43c4-b488-91b3dd79374d)

![Screenshot_2023-08-08-21-20-18-47_b4450e33c7076f102e79bbedaff38911.jpg](https://github.com/maxrave-dev/SimpMusic/assets/76624594/9fc8a715-7dbf-4e9c-9248-67430345999e)

**Comment by maxrave-dev** [comment]
I am trying to fix this, but I don't have too much phone with multiple dpi and screen size to test this. Sorry for this problem

**Comment by d4f5409d** [comment]
> I am trying to fix this, but I don't have too much phone with multiple dpi and screen size to test this. Sorry for this problem

Android Studio doesn't help either? I think there are mobile presets which imitate the screens as well. (OnePlus 8)
