### ISSUE TITLE
Spotify Canvas isn't working

### ISSUE THREAD

**Issue by uasaad** [maxrave-dev/SimpMusic#313]
Spotify Canvas option isn't working in my phone, tried with my brother's android 12 phone also. Logged in with Spotify and YouTube too.

**Comment by maxrave-dev** [comment]
Give me more screenshots

**Comment by uasaad** [comment]
![Screenshot_2024-03-15-14-03-26-936_com maxrave simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/102511630/33c14783-ee62-402a-b98e-f9c54323f201)
![Screenshot_2024-03-15-14-03-07-464_com maxrave simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/102511630/579eb963-ae7d-42ce-9684-8ed1b2c80eaa)
![Screenshot_2024-03-15-14-02-17-565_com maxrave simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/102511630/d55b9842-5c86-4aa6-8933-33ef20aed596)

**Comment by maxrave-dev** [comment]
Try to enable Spotify Lyrics

**Comment by uasaad** [comment]
Still doesn't work :"(

**Comment by owencz1998** [comment]
Try to force close it and clear cache.

If not try and backup and clear data.

**Comment by uasaad** [comment]
It's not working no matter what I do. 
Is it just me? Is it working on your phone?

**Comment by owencz1998** [comment]
Yeah it's working for me perfectly what about try logging out of your account and login again.

**Comment by maxrave-dev** [comment]
@uasaad hey can you try to change Spotify account or change region of your Spotify account or use VPN. Spotify Canvas dont have any official documentation so I need to research, reference from other repo and test on my account, so I don't know why caused! Can you share me more information like region of you and Spotify Account, type of account, etc

**Comment by uasaad** [comment]
Just tried with some vpns, didn't work.
So, i am from Bangladesh. I set the region to BD (i also tried with other regions)
I have a Spotify free account.

@maxrave-dev just knocked you in discord, feel free to ask anything about this issue there or here

**Comment by maxrave-dev** [comment]
Depend on your account or your country, if your Spotify app doesn't show, SimpMusic doesn't show too

**Comment by uasaad** [comment]
@maxrave-dev My uncle uses spotify premium. He has the canvas feature in his phone.
I don't think it's a "premium only" or "Regional" feature

**Comment by Amara97-sysz** [comment]
same problem here. I just download my Spotify playlists to MP3 via Tunelf and listen to them without canvas

**Comment by estevezmanuel029-coder** [comment]
Tengo el mismo problema  tengo  un teléfono con miui 13 lo actualice al miui 14 será por eso que dejaron de aparecer los canvas en simpmusic ?
