### ISSUE TITLE
Store downloads on external storage (SD Card)

### ISSUE THREAD

**Issue by Djkcool** [maxrave-dev/SimpMusic#323]
**Is your feature request related to a problem? Please describe.**
No, but I normally store downloaded music on external storage as it can take up a lot of space.

**Describe the solution you'd like**
It would be nice if there was an option to store downloaded music on external storage (ex. SD Card) like in other music streaming apps like Spotify or choose a path to store the music, instead of just using the app's default download path.

**Comment by dskzero22** [comment]
I was going to suggest the same thing, is necessary

**Comment by emulatoronlinexyz** [comment]
Yeah that must be added to the app.

**Comment by maxrave-dev** [comment]
Not a music downloader

**Comment by Djkcool** [comment]
> Not a music downloader
 
The suggestion isn't to have it download music separately, but to rather extend the current ability to download songs to add the option of downloading to the SD Card, purely for storage reasons. It's the same as the current download system except you would use the SD Cards protected Data folder, I think.
<br> If the intention isn't to allow downloading songs at all why is that a feature that is currently available? This is in essence the same thing just allowing you to store songs on external storage, its not like a user can easily access those files.

**Comment by da-anda** [comment]
I would also welcome to be able to choose if downloads should end up in internal storage or SD card. My internal storage is too limited in order to hold a larger download cache, thus I would also welcome the ability to move it to the SD card (even YT Music app does allow to use the SD card for the dl cache). Thanks.
