### ISSUE TITLE
Spotify Sharing

### ISSUE THREAD

**Issue by Kabuki1212** [maxrave-dev/SimpMusic#326]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kabuki1212** [comment]
idea for shareing playlists and songs from spotify

**Comment by maxrave-dev** [comment]
https://github.com/sigma67/spotify_to_ytmusic
Use this library to convert Spotify Playlist to YouTube Music Playlist
