### ISSUE TITLE
Search removal not effective

### ISSUE THREAD

**Issue by kfrack3** [maxrave-dev/SimpMusic#334]
**Describe the bug**
When I try to remove a search, it doesn't remove the search I click, and instead removes the one below it.

**To Reproduce**
1. Conduct multiple searches
2. Click on the 'x'
3. The removal will happen for the search below the one you picked

**Expected behavior**
It should remove the search I clicked.

**Comment by maxrave-dev** [comment]
I see, thanks for reporting!
