### ISSUE TITLE
Not able to add songs in a playlist

### ISSUE THREAD

**Issue by aneesh1122** [maxrave-dev/SimpMusic#344]
**Describe the bug**

**To Reproduce**
1. Go to any song
2. Click on 'add to a playlist'

**Expected behavior**

A list of all the playlists should appear to choose from, both local and from YouTube

**Screenshots**

https://github.com/maxrave-dev/SimpMusic/assets/45353488/a3af37e4-c0f7-4a2b-b0cd-3574ccb6b65a

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by aneesh1122** [comment]
I didn't know I had to add it as a local playlist first to add songs. Closing this issue

**Comment by kiwi5321** [comment]
Can u explain how to fix this again because I'm having the same issue

**Comment by AnetaSkoniecka** [comment]
You neet to go to library, create new local playlist, restart App, open App again, select Song and the you are able to add to playlist
