### ISSUE TITLE
Queuing up a song in an empty queue prevents the player UI from showing up

### ISSUE THREAD

**Issue by 14142000** [maxrave-dev/SimpMusic#345]
**Describe the bug**
When clearing the queue and then adding songs to it to try to create a temporary playlist, the player UI at the bottom of the screen does not show up, not allowing you to pause modify the queue or scrub through the songs.

**To Reproduce**
1. Go to simp music
2. Swipe on the player to expose the ex that clears your queue and tap it
3. Scroll down to The music that you want to add to queue and press the three dots next to it and tap on add to queue

**Expected behavior**
The player UI would show showing the first song added to queue 

**Screenshots**

https://github.com/maxrave-dev/SimpMusic/assets/3375830/0b0c7f35-031c-4573-91b2-3d659d84484d

**Comment by maxrave-dev** [comment]
Oh, I try but I don't have this problem, Please tell more about the steps to have this issue

**Comment by 14142000** [comment]
I only use synced playlists from youtube music, so that perhaps is a factor

**Comment by 14142000** [comment]
Is there any other information I could possibly give you to help fix this?

**Comment by maxrave-dev** [comment]
I fixed this issue

**Comment by 14142000** [comment]
Its still happening on the latest build
