### ISSUE TITLE
Status bar and Navigation bar not transparent

### ISSUE THREAD

**Issue by ChosenProgram** [maxrave-dev/SimpMusic#35]
Is there a way for simpmusic to use the android api to make the navbar transparent? Also, although on stock android, the status bar is transparent, on Samsung devices, there's like a little tint that remains which looks weird~

**Comment by maxrave-dev** [comment]
I need more information, such as screenshot, device... By the way, all my phone I tested still have translucent status bar

**Comment by ChosenProgram** [comment]
![20230812_105258.png](https://github.![Screenshot_20230812_105234_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/126732466/9b7f6921-e8f6-4926-b7e3-9e2063bcec97)

14-b320-9ad64ba3a97a)

![Uploading Screenshot_20230812_105234_SimpMusic.png …]()

Is there anything that can be done about it?

**Comment by maxrave-dev** [comment]
I can't see your picture

**Comment by ChosenProgram** [comment]
I'll just send thru email instead

**Comment by maxrave-dev** [comment]
Oh, i don't set navbar, only status bar translucent

**Comment by maxrave-dev** [comment]
Translucent navigation bar is available now
