### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by 6801318d8d** [maxrave-dev/SimpMusic#351]
**Describe the bug**

When in the Home tab, I scroll down to "Let's pick a playlist for you" section, then in "Genre" subsection I scroll rightr and click on "Metal", whatever I click under "Today's Metal Hits" (for example "Metal Hotlist"), SimpMusic goes into infinite looping.

A spinning wheel is shown and it never ends.

**To Reproduce**
See above

**Expected behavior**
The playlist should be shown

**Screenshots**
![simp](https://github.com/maxrave-dev/SimpMusic/assets/144167388/87da690f-e87f-4fbe-82fe-4e10674167b1)

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by maxrave-dev** [comment]
Where is your country? YouTube data depend on country so I can't test for all

**Comment by 6801318d8d** [comment]
> Where is your country? YouTube data depend on country so I can't test for all

Italy

**Comment by RedNas74** [comment]
I have the same problem. My region is Netherlands.
