### ISSUE TITLE
performance: faster load times

### ISSUE THREAD

**Issue by mirsella** [maxrave-dev/SimpMusic#365]
Thanks for this awesome project ! Of course this is just feedback, and your project is already incredible !

**Is your feature request related to a problem? Please describe.**
Compared to the official yt music or innertube where loading times are instant (launching the app fresh to playing music from a playlist) simpmusic is a lot slower. 

**Describe the solution you'd like**
i don't know the underlying difference for this, but maybe simpmusic could cache better some elements, like playlist data. it *seems* like it's loading freshly from the server everytime.

**Additional context**
personally, I hate waiting for things, especially when I'm out, and I want to start my music rapidly. simpmusic take me 3x more times and frustration for me to start my playlist. i would gladly screenrecord the diff if this seems exaggerated, or if it seems like a problem on my device.

thanks and have a great day !

**Comment by maxrave-dev** [comment]
Did you try latest version?

**Comment by mirsella** [comment]
no, I was on the latest at the date of the issue, will try again !

**Comment by mirsella** [comment]
freshly opening the app is now so much faster ! thanks !
I can start the audio payback practically without waiting
