### ISSUE TITLE
Không đẩy bài hát được phát tiếp theo lên sau bài đang phát

### ISSUE THREAD

**Issue by aycact** [maxrave-dev/SimpMusic#370]
Khi dùng tính năng phát tiếp theo thì bài hát nào đã được thêm vào hàng đợi sẽ không được đẩy lên sau bài đang phát mà vẫn đứng ở thứ tự đó![Screenshot_20240509-090709_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/93394403/e34da8bd-62df-42e5-9f08-4bdb50152783)

**Comment by maxrave-dev** [comment]
Fixed in latest build
