### ISSUE TITLE
Background listening 

### ISSUE THREAD

**Issue by itsyourboiearltuyay** [maxrave-dev/SimpMusic#372]
Add background playback listening, it would be nice.

**Comment by CrazyWolf13** [comment]
Opening the app, start playing something, put the app to the background, -> background playback works just fine and as expected for me.

Maybe you need to turn off battery optimisation ?

**Comment by itsyourboiearltuyay** [comment]
Well, it does work.But I want it to still play music. Even I have removed it from the background like innertune or Vimusic

**Comment by CrazyWolf13** [comment]
So you want a full background playback, not an android developer, but I heard that it's very difficult to implement this, as many vendors have very agressive background regulations and spp killing.

Also I'm not sure what the benefit of this would be?

Just so you can swipe up to close simpmusic and it continues?
