### ISSUE TITLE
Added date with button

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#378]
New commit is missing the added date button.

![Screenshot_20240519_084416_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/96573836-9c1a-438f-9a23-889f8b29c1f9)

![Screenshot_20240519_084409_SimpMusic Debug.jpg](https://github.com/maxrave-dev/SimpMusic/assets/96526481/378c2aaf-9804-463d-af00-9eecd706c290)

**Comment by maxrave-dev** [comment]
I added in latest commit
