### ISSUE TITLE
Option for HIGH (320 KBPS) Audio quality 

### ISSUE THREAD

**Issue by TakiShiwa** [maxrave-dev/SimpMusic#38]
Can you please add 270 and 320 kbps audio quality options also?

**Comment by maxrave-dev** [comment]
How to get 320kps with free access from YouTube?

**Comment by TakiShiwa** [comment]
I genuinely don't know but here is an open source app which can pull 320 kbps audio from YouTube and Jiosaavn (Indian Spotify)

**Comment by maxrave-dev** [comment]
Maximum from YT is 129. Also, some app convert to more kps but quality dont change.

**Comment by TakiShiwa** [comment]
https://github.com/Sangwan5688/BlackHole

**Comment by TakiShiwa** [comment]
> Maximum from YT is 129. Also, some app convert to more kps but quality dont change.

Oh

**Comment by max5354** [comment]
> How to get 320kps with free access from YouTube?

We can't get 320kbps for free but we can get 256kbps for free even blackhole gives 256kbps for free. Also it will be great if you add 256kbps quality also

**Comment by Carter0108** [comment]
To add to this, whilst 320kbps absolutely isn't possible from YT Music, could we not have the option for 256kbps for users logged in with a Premium account?

**Comment by maxrave-dev** [comment]
@TakiShiwa [BlackHole](https://github.com/Sangwan5688/BlackHole) is using music source from [Jiosaavn](https://www.jiosaavn.com/). I don't know this service, but this does not have all tracks from YouTube Music and YouTube. So I am not planing to use this service for my app. Thanks <3

**Comment by TakiShiwa** [comment]
> @TakiShiwa [BlackHole](https://github.com/Sangwan5688/BlackHole) is using music source from [Jiosaavn](https://www.jiosaavn.com/). I don't know this service, but this does not have all tracks from YouTube Music and YouTube. So I am not planing to use this service for my app. Thanks <3

I certainly believe but it lets you choose the source ![IMG_20230915_111221.jpg](https://github.com/maxrave-dev/SimpMusic/assets/137756384/2be204f1-00dd-462a-a033-708f7d7bd40b)

**Comment by maxrave-dev** [comment]
![image](https://github.com/maxrave-dev/SimpMusic/assets/113747128/95a16868-99d3-4c9e-a912-b645384ce74f)
Here is API this repo use

**Comment by maxrave-dev** [comment]
@TakiShiwa and if you choose YTMusic, BlackHole can't provide 320kps quality

**Comment by TakiShiwa** [comment]
> @TakiShiwa and if you choose YTMusic, BlackHole can't provide 320kps quality

Yeah I see. It downloaded a m4a file not a mp3
![Screenshot_2023-09-15-11-24-11-29_db51e592e420a9871f4a37915a68789b.jpg](https://github.com/maxrave-dev/SimpMusic/assets/137756384/d8aabae3-4616-42c7-8c2e-2550df2b9b33)

**Comment by TakiShiwa** [comment]
How about adding the saavn option also, so that ppl can choose from where to download
Songs downloaded from saavn will download in 320 kbps and any other in lower quality

**Comment by maxrave-dev** [comment]
Supported maximum 256kps quality

**Comment by TakiShiwa** [comment]
> Supported maximum 256kps quality

Hurrah!

**Comment by maxrave-dev** [comment]
> > Supported maximum 256kps quality
> 
> 
> 
> Hurrah!

From 0.2.1 ver, for YouTube Music Premium user

**Comment by TakiShiwa** [comment]
Damm it, I do not have premium, by the way, I am not able to log in by Spotify
