### ISSUE TITLE
Debug builds are laggy

### ISSUE THREAD

**Issue by Datokina** [maxrave-dev/SimpMusic#381]
**Describe the bug**
All debug builds are very laggy on my device (SM-G975F, running on android 12)

**To Reproduce**
1. Install any debug device
2. Open the app
3. Scroll up and down the home page
4. Experience the lagging

**Expected behavior**
Should be smooth as it's intended to be.

**Comment by sabbaghpierre** [comment]
Debug builds are always laggier than the release ones, a solution would be to provide beta or alpha release candidates when some features are fixed or added.

**Comment by sabbaghpierre** [comment]
It's expected as Compose is still relatively new.

If you can provide debug or release candidates for the app, we could test the performance on our devices and give you more feedback.

**Comment by Datokina** [comment]
> I don't know why, but when I change Local Playlist layout to Compose, the app is too lag. I try to make app beautiful but it make app so lag

It's okay as my device is quite old, I haven't heard from anyone about lagging.

**Comment by maxrave-dev** [comment]
I changed the workflow to build a release apk, try it and report to me

**Comment by Datokina** [comment]
> I changed the workflow to build a release apk, try it and report to me

Didn't work. Is the apk unsigned? If so, my phone is currently unrooted so I can't install it.
