### ISSUE TITLE
Outdated on F-Droid

### ISSUE THREAD

**Issue by CrazyWolf13** [maxrave-dev/SimpMusic#384]
**Describe the bug**
Latest version on F-Droid is outdated

**To Reproduce**
1. Download from F-Droid
2. Get greeted with a please update node
3. have to upgrade from GitHub

**Expected behavior**
If there is F-Droid, I expect it to be up to date, after 2 months.

Btw: This app is amazing!!

Thanks for creating this masterpiece :)

**Comment by maxrave-dev** [comment]
Sorry, because some changes in my repo, so F-droid can't build for current version, please wait for next build

**Comment by CrazyWolf13** [comment]
> Sorry, because some changes in my repo, so F-droid can't build for current version, please wait for next build

Oh I see, yeah sure no problem, appreciate the reply :)
