### ISSUE TITLE
Musixmatch login not working

### ISSUE THREAD

**Issue by aemogie** [maxrave-dev/SimpMusic#386]
**Describe the bug**
Musixmatch login screen shows "Error" on entering without doing anything. Then it always shows "Wrong Credentials" even when I have confirmed login works on the website.

**To Reproduce**
1. Go to Settings
2. Go to 'Log in to Musixmatch'
3. Click on it to immediately see an "Error" toast
4. Try logging in to see "Wrong Credentials" as well

**Expected behavior**
Login has no error toasts, and allows logging in.

**Screenshots**
![Error toast](https://github.com/maxrave-dev/SimpMusic/assets/54412618/bd995012-6969-4201-9f95-043d44007580)
![Wrong Credentials toast](https://github.com/maxrave-dev/SimpMusic/assets/54412618/ca40b88c-3c60-4c2b-a915-dec50d60383d)

**Comment by aemogie** [comment]
Not the bug report, but wouldn't asking to enter the API key directly solve this?

**Comment by aemogie** [comment]
Tried a regular musixmatch community login just in case and that worked. Seems it wasn't expecting a developer login, despite the README linking to that. Curious.

**Comment by kris20030705** [comment]
Just make account using temp mail and log in

**Comment by aemogie** [comment]
Sorry if I was unclear. I had no issues with emails, just that the developer login is different from the community login. The README as well as the settings option label leads to the developer login, but the community login is what is used.

I did manage to login, this wasn't meant as a support request, but as a bug report. Sorry if this came off otherwise.

(Although it does say logged in, I haven't had any lyrics yet, so I'm not sure it worked, but that's a different issue which also isn't reproducible, so opening an issue would be pointless)

**Comment by kris20030705** [comment]
> Sorry if I was unclear. I had no issues with emails, just that the developer login is different from the community login. The README as well as the settings option label leads to the developer login, but the community login is what is used in the in-app login.
> 
> I did manage to login, this wasn't meant as a support request, but as a bug report. Sorry if this came off otherwise.
> 
> (Although it does say logged in, I haven't had any lyrics yet, so I'm not sure it worked, but that's a different issue which also isn't reproducible, so opening an issue would be pointless)

Yeah i faced it too maybe change issue title as "lyrics not showing"
Lyrics only load on some songs

**Comment by Datokina** [comment]
> > Sorry if I was unclear. I had no issues with emails, just that the developer login is different from the community login. The README as well as the settings option label leads to the developer login, but the community login is what is used in the in-app login.
> > I did manage to login, this wasn't meant as a support request, but as a bug report. Sorry if this came off otherwise.
> > (Although it does say logged in, I haven't had any lyrics yet, so I'm not sure it worked, but that's a different issue which also isn't reproducible, so opening an issue would be pointless)
> 
> Yeah i faced it too maybe change issue title as "lyrics not showing" Lyrics only load on some songs

The lyrics work on the debug ver atleast

**Comment by RolexxxandeR** [comment]
> > > Lo siento si no estaba claro. No tuve problemas con los correos electrónicos, solo que el inicio de sesión del desarrollador es diferente del inicio de sesión de la comunidad. El archivo README y la etiqueta de opción de configuración conducen al inicio de sesión del desarrollador, pero el inicio de sesión de la comunidad es lo que se utiliza en el inicio de sesión en la aplicación. 
> > > Logré iniciar sesión, esto no fue una solicitud de soporte, sino un informe de error. Lo siento si esto salió de otra manera. 
> > > (Aunque dice haber iniciado sesión, todavía no tengo ninguna letra, así que no estoy seguro de que haya funcionado, pero ese es un problema diferente que tampoco es reproducible, por lo que abrir un problema no tendría sentido)
> > 
> > 
> > Sí, yo también lo enfrenté, tal vez cambie el título del número porque "las letras no se muestran". Las letras solo se cargan en algunas canciones.
> 
> La letra funciona en la versión de depuración.



> > Lo siento si no estaba claro. No tuve problemas con los correos electrónicos, solo que el inicio de sesión del desarrollador es diferente del inicio de sesión de la comunidad. El archivo README y la etiqueta de opción de configuración conducen al inicio de sesión del desarrollador, pero el inicio de sesión de la comunidad es lo que se utiliza en el inicio de sesión en la aplicación.
> > Logré iniciar sesión, esto no fue una solicitud de soporte, sino un informe de error. Lo siento si esto salió de otra manera.
> > (Aunque dice haber iniciado sesión, todavía no tengo ninguna letra, así que no estoy seguro de que haya funcionado, pero ese es un problema diferente que tampoco es reproducible, por lo que abrir un problema no tendría sentido)
> 
> Sí, yo también lo enfrenté, tal vez cambie el título del número porque "las letras no se muestran". Las letras solo se cargan en algunas canciones.


I agree because since Musixmatch fails, most of the song lyrics do not appear or lyrics from other songs appear.

**Comment by maxrave-dev** [comment]
> Sorry if I was unclear. I had no issues with emails, just that the developer login is different from the community login. The README as well as the settings option label leads to the developer login, but the community login is what is used in the in-app login.
> 
> I did manage to login, this wasn't meant as a support request, but as a bug report. Sorry if this came off otherwise.
> 
> (Although it does say logged in, I haven't had any lyrics yet, so I'm not sure it worked, but that's a different issue which also isn't reproducible, so opening an issue would be pointless)

Musixmatch search engine is dead. So I implemented Lrclib in latest commits to quickly fix this issue.

**Comment by maxrave-dev** [comment]
I test the login still working. Does anyone still have issues?
