### ISSUE TITLE
Lỗi đăng nhập spotify bằng tài khoản Google

### ISSUE THREAD

**Issue by aycact** [maxrave-dev/SimpMusic#390]
**Describe the bug**
Đăng nhập spotify bằng tài khoản Google thì gặp lỗi này

**Screenshots**
![Screenshot_20240602-202018_SimpMusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/93394403/e028605c-f2d7-47a0-a028-9c0383e62f07)

**Comment by maxrave-dev** [comment]
Bạn thử update webview hoặc đổi system webview sang Chrome bên trong Developer Setting của máy nhé
