### ISSUE TITLE
Lyrics not showing

### ISSUE THREAD

**Issue by Udayg1** [maxrave-dev/SimpMusic#391]
**To Reproduce**
1. Get simpmusic 
2. Play a song 
3. Lyrics not showing

**Expected behavior**
Lyrics to be displayed.

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by assier08** [comment]
The same happens to me
![Screenshot_2024-06-18-17-28-07-755_com maxrave simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/172515042/c99a74d6-25fa-4e3a-8ab9-c6c8e4f062c5)

**Comment by bmtarek79** [comment]
Same here no lyrics showed
