### ISSUE TITLE
Ui problem 

### ISSUE THREAD

**Issue by Shivamhobbyist** [maxrave-dev/SimpMusic#4]
![Screenshot_20230730_073211_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/78287172/7fe2421e-8419-467d-a6cb-7479ae9c0f29)

Navigation button is to bottom 
Samsung galaxy a34 5g
Android 13 One UI 5.1

**Comment by maxrave-dev** [comment]
Can you show me a full screenshot?

**Comment by Shivamhobbyist** [comment]
> Can you show me a full screenshot?

It's full screenshot from chin to front camera

**Comment by maxrave-dev** [comment]
Go to Device Settings -> Display and increase your DPI. It may be fixed temporarily.

**Comment by Shivamhobbyist** [comment]
> Go to Device Settings -> Display and increase your DPI. It may be fixed temporarily.

Okay let's see

**Comment by Shivamhobbyist** [comment]
> Go to Device Settings -> Display and increase your DPI. It may be fixed temporarily.

When I set 440dpi it's perfect like GitHub ss but overall phone screen to small![Screenshot_20230730_080150_Settings.png](https://github.com/maxrave-dev/SimpMusic/assets/78287172/662ca2d7-dfc1-4cd0-824d-6582ef972ed4)

**Comment by maxrave-dev** [comment]
@Shivamhobbyist thanks for reporting, i will fix this problem in next build

**Comment by Shivamhobbyist** [comment]
> @Shivamhobbyist thanks for reporting, i will fix this problem in next build

![Screenshot_20230904_235700_SimpMusic.png](https://github.com/maxrave-dev/SimpMusic/assets/78287172/fda9fcb8-f54e-49be-87de-df2f0ac38bd9)

Still not fix
Samsung galaxy a34 5g
Android 13 One UI 5.1

**Comment by maxrave-dev** [comment]
> > @Shivamhobbyist thanks for reporting, i will fix this problem in next build
> 
> ![Screenshot_20230904_235700_SimpMusic.png](https://user-images.githubusercontent.com/78287172/265524953-fda9fcb8-f54e-49be-87de-df2f0ac38bd9.png)
> 
> Still not fix Samsung galaxy a34 5g Android 13 One UI 5.1

Can you give me your device's DPI and Screen Size

**Comment by Shivamhobbyist** [comment]
![Screenshot_20230906_070658.png](https://github.com/maxrave-dev/SimpMusic/assets/78287172/2473f750-b971-4977-992c-ddf7543dbb65)
