### ISSUE TITLE
I can't play the playlist , when I click on it it shows null error

### ISSUE THREAD

**Issue by hagiangson** [maxrave-dev/SimpMusic#404]
![Screenshot_2024-06-24-03-40-35-390_com.maxrave.simpmusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/173635236/c148f952-d9a1-45a6-8a38-b727957b15b7)

![Screenshot_2024-06-24-03-37-59-691_com.maxrave.simpmusic.jpg](https://github.com/maxrave-dev/SimpMusic/assets/173635236/90145dfe-6b1b-441f-83d8-ee3f89baeacf)

**Comment by maxrave-dev** [comment]
#401 Fixed in latest nightly build

**Comment by blueberrie231** [comment]
Hiya, I'm having the same issue and I don't know how to fix it. None of my YouTube playlists are working

**Comment by WHONEYR** [comment]
> #401 Fixed in latest nightly build

How do I download the nightly build?

**Comment by maxrave-dev** [comment]
You need to log in to Github and go to Actions page of my repo and you see the artifacts then download it

**Comment by maxrave-dev** [comment]
In readme page, click to nightly download
