### ISSUE TITLE
Null/Error Codes

### ISSUE THREAD

**Issue by blueberrie231** [maxrave-dev/SimpMusic#405]
Hiya, every time I try to open a playlist either from my imported YouTube playlists or suggested from the app it says it can't open it and there's an error code.

**Comment by WHONEYR** [comment]
Yeah this also happen with albums

**Comment by sirdx** [comment]
Duplicate of #401

**Comment by maxrave-dev** [comment]
Fixed f7959f33aa746cf88a17403a4539d0c10b4e02d7
