### ISSUE TITLE
Can't download nightly build

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#406]
It just throws error 404 ![Screenshot_20240625-021637_Chrome.jpg](https://github.com/maxrave-dev/SimpMusic/assets/118454718/ce03ee4e-089c-4bdf-9163-3d2106fad283)

I tried to check the suggested link, after logging in I see same error

**Comment by WHONEYR** [comment]
Where's the link??

**Comment by maxrave-dev** [comment]
Fixed so you can download again
