### ISSUE TITLE
Playlist error

### ISSUE THREAD

**Issue by Yanphat2k8** [maxrave-dev/SimpMusic#407]
A bug make me can't enter a my playlist, tap on but trust have a note "error" 

1. Go to 'library "
2. Click on playlish
3. See error

Can you fix it please! 

**Screenshots**

![Screenshot_20240625-145651_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/165274558/c1cc1889-2613-4605-a7f0-69eb1b39d40d)

![Screenshot_20240625-145659_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/165274558/ea042d3d-e97e-4987-b682-243103cc4ddb)

![Screenshot_20240625-145251_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/165274558/94b311b6-8929-4ea9-9352-78387851f502)

**Comment by maxrave-dev** [comment]
Check #401, if nightly build work, close this issue

**Comment by Zdertis420** [comment]
> Check #401, if nightly build work, close this issue

Nightly build fixed bug with albums but not playlists. I also can't open them but albums are ok
