### ISSUE TITLE
Bad performance in nightly build 

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#408]
After I faced a bug described in couple of latest issues I installed a nightly build and it's performance is terrible. Is my phone just too old (I'm using Samsung galaxy note 10)? Or it is a real problem?

**Comment by sirdx** [comment]
I suppose it is because of the app being build in debug mode.

**Comment by Zdertis420** [comment]
> I suppose it is because of the app being build in debug mode. 
> Take a look at #381.

> Thanks

**Comment by maxrave-dev** [comment]
I changed the workflow to build a release apk, try it and report to me @Zdertis420

**Comment by Zdertis420** [comment]
> I changed the workflow to build a release apk, try it and report to me @Zdertis420 

I think you you released it as new nightly build and it's corrupted...

![Screenshot_20240625-192359_Package installer.jpg](https://github.com/maxrave-dev/SimpMusic/assets/118454718/09aca6e2-8aa7-4c0e-83fe-1a36fea4960b)
Update app?

![Screenshot_20240625-192404_Package installer.jpg](https://github.com/maxrave-dev/SimpMusic/assets/118454718/3ef8bdf5-e3df-4118-b5da-e7367e0fdce1)

App isn't installed because it's package is not valid (for example corrupted)

**Comment by maxrave-dev** [comment]
Nightly ver is CI CD build from Github Actions and unsigned build. It will conflict with release ver.
You have two choices:
- Debug but lag
- Now, smooth
