### ISSUE TITLE
Latest nightly builds aren't installable

### ISSUE THREAD

**Issue by kairusds** [maxrave-dev/SimpMusic#410]
**Describe the bug**
The commit 5091f3b seems to have broken nightly builds entirely, which results in APK files that can't be installed.

**To Reproduce**
1. Download the nightly builds from the workflows of commit 5091f3b to the latest ones.

**Expected behavior**
The apk file should be installable.

**Screenshots**

**Log (Error Details)**

**Comment by ddavidd** [comment]
Just leaving a comment to note that the latest nightly build works for me.

**Comment by kairusds** [comment]
> Just leaving a comment to note that the latest nightly build works for me.

I can't install unsigned APK files on Android 11.

**Comment by kairusds** [comment]
Seems like 77839ab fixed it.
