### ISSUE TITLE
Playlists don't open

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#411]
Iv seen that its been fixed in the commits but it still giving a error trying to open my playlist mate @maxrave-dev

**Comment by 14142000** [comment]
Youtube changed the api, all third party apps have this issue.

**Comment by Zdertis420** [comment]
> Youtube changed the api, all third party apps have this issue. 

We are rooting for maxrave-dev

**Comment by maxrave-dev** [comment]
I don't have any error. Please try download again

**Comment by bschatzow** [comment]
I get an error as well.  Re-downloaded and still an issue

**Comment by maxrave-dev** [comment]
[screencast-Genymotion-2024-06-26_19.28.12.51.webm](https://github.com/maxrave-dev/SimpMusic/assets/113747128/5d72ac3d-e6b6-40db-b739-00782cc7549d)
I don't know why. What is your language and region @bschatzow @owencz1998

**Comment by owencz1998** [comment]
I'm from the United kingdom mate @maxrave-dev

**Comment by maxrave-dev** [comment]
[screencast-Genymotion-2024-06-26_19.55.55.447.webm](https://github.com/maxrave-dev/SimpMusic/assets/113747128/3620f770-fd90-4804-b1e1-748f54eca199)
Why this work, so I need to use VPN to test more

**Comment by maxrave-dev** [comment]
@owencz1998 https://github.com/maxrave-dev/SimpMusic/assets/113747128/6af9b931-7ff9-41c7-8611-5d738fb9e510

**Comment by maxrave-dev** [comment]
Worked normal in London

**Comment by owencz1998** [comment]
https://github.com/maxrave-dev/SimpMusic/assets/96526481/1b1cfc4a-c523-4330-bce4-b3e4f3dbc830

@maxrave-dev

**Comment by reixerus** [comment]
Same here, it doesn't work.

**Comment by maxrave-dev** [comment]
https://github.com/maxrave-dev/SimpMusic/actions/runs/9680612197 Try this

**Comment by reixerus** [comment]
> https://github.com/maxrave-dev/SimpMusic/actions/runs/9680612197 Try this

It works now, thank you!

**Comment by owencz1998** [comment]
Awesome it works thanks @maxrave-dev

**Comment by bschatzow** [comment]
> [screencast-Genymotion-2024-06-26_19.28.12.51.webm](https://github.com/maxrave-dev/SimpMusic/assets/113747128/5d72ac3d-e6b6-40db-b739-00782cc7549d) I don't know why. What is your language and region @bschatzow @owencz1998

English, US

**Comment by Zdertis420** [comment]
Yooooo, I finally got a new phone and everything works as should! So for me problem occured because of my old phone

**Comment by bschatzow** [comment]
Update fixed it for me.
