### ISSUE TITLE
Sort music bug

### ISSUE THREAD

**Issue by owencz1998** [maxrave-dev/SimpMusic#414]
Found a glitch with sort music button hmmm never seen this before 😂

https://github.com/maxrave-dev/SimpMusic/assets/96526481/f8a284ff-6bea-4572-8f9e-38f56f83aabf

**Comment by maxrave-dev** [comment]
Sync to YouTube Music, then remove this playlist, finally sync this again

**Comment by maxrave-dev** [comment]
May be database corrupted after install many debug build 🥹🥹🥹

**Comment by owencz1998** [comment]
This didn't solve the issue unfortunately @maxrave-dev 😔😔
