### ISSUE TITLE
Is LRCLIB integrated in debug apk ? Still not fetching lyrics

### ISSUE THREAD

**Issue by Its-Tony** [maxrave-dev/SimpMusic#415]
Musixmatch and Spotify lyrics not working(only working for EN songs), Since you have integrated LRCLIB api,still lyrics are not available.Is it available for coming in next update. There is an app RiMusic it have a feature (picks from lrclib) which allow user to select from multiple lyrics file if it is not best match with timestamps.
Also, you can add kuGou api (https://github.com/keyule/KuGou-API) for Backup source(major source for Chinese language, some global songs lyrics are also available).
Finally, When will be the next stable release?

**Comment by maxrave-dev** [comment]
All most lyrics have been shown okay since I implemented LRCLIB. So what song you have issues

**Comment by Logan7899** [comment]
> All most lyrics have been shown okay since I implemented LRCLIB. So what song you have issues

When the new version will be released because I am getting error while opening albums and playlist

**Comment by maxrave-dev** [comment]
@Logan7899  #401

**Comment by Its-Tony** [comment]
Not available for Indian songs, I have tried both source, multiple songs. Working fine only for English songs. (LRCLIB have lyrics for same song).
Screenshot attached. Please have a look on this issue Sir. 
![Screenshot_2024-06-29-08-23-41-296_com maxrave simpmusic dev~2](https://github.com/maxrave-dev/SimpMusic/assets/172184183/81143e75-46d1-4fec-9511-8ad6ba8531a5)
![Screenshot_2024-06-29-08-24-53-605_com android chrome~2](https://github.com/maxrave-dev/SimpMusic/assets/172184183/a88cb519-86a6-4246-91de-d9e11e01cf27)
