### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by Wetsnot123** [maxrave-dev/SimpMusic#416]
On the app simp music, everything is almost perfect but everytime I click on an album or playlist it sends me back to the start of the app or the home part and says either error or null. I checked for any updates, restarted the app numerous times and nothing seems to be working, and this is with all the albums not just one. This pretty annoying telling that I really like this app and it would be so much better if I could actually play an album instead searching every song individualy from the album that I want to listen to. Please fix this

**Comment by Logan7899** [comment]
Yaa i am also facing that

**Comment by Wetsnot123** [comment]
If you ever find out out how to fix it. Let me know

**Comment by attilafekete73** [comment]
I also have this. Please fix it because it's so annoying

**Comment by maxrave-dev** [comment]
#401
