### ISSUE TITLE
request: kotlinYTmusic scraper lib update

### ISSUE THREAD

**Issue by IndusAryan** [maxrave-dev/SimpMusic#425]
Hi there, the library https://github.com/maxrave-dev/kotlin-youtubeExtractor is good but why it is archived with no updates, please  update it with the library that is embedded in the app, it is broken since long, and now more with recent yt api changes,  It is the only good lib with straight forward use and docs.

**Comment by maxrave-dev** [comment]
You can bring all code in kotlinYtmusicScraper to your project and follow GPL 3.0 license

**Comment by maxrave-dev** [comment]
And this is in SimpMusic, of course

**Comment by IndusAryan** [comment]
alright, thanks.
