### ISSUE TITLE
Cannot add songs to playlist 

### ISSUE THREAD

**Issue by LaKinguin** [maxrave-dev/SimpMusic#426]
Everytime I try to add a song to my playlist, it just doesn't have a pop up for which playlist I'm adding it to. ![Uploading Screenshot_20240703-075903.png …]()

This is what it looks like

**Comment by maxrave-dev** [comment]
Your picture haven't been uploaded

**Comment by LaKinguin** [comment]
![Screenshot_20240718-094621.png](https://github.com/user-attachments/assets/19d8b77e-d404-4800-807d-4f39e0cb4276)

here it is

**Comment by maxrave-dev** [comment]
Do you have any local playlists?

**Comment by LaKinguin** [comment]
no i don't

**Comment by LaKinguin** [comment]
also the app is a bit laggy on my phone. like when i play my playlist it freezes for a bit. and when i tried to download songs, on the notification bar it says "download completed" but they aren't anywhere on my phone

**Comment by maxrave-dev** [comment]
Create new local playlist
