### ISSUE TITLE
Music stopping prematurly

### ISSUE THREAD

**Issue by Moonwaffles22** [maxrave-dev/SimpMusic#434]
1, describing) I play a few songs, a total of 8-9, and then it stops and the Playlist freezes, stating I don't have a stable internet connection when I do

2, to reproduce)
-1 Start up a Playlist, mine had over a 100
-2 Either shuffle or not, I had mine usually set to shuffle
-3 It'll then crap out shortly after the couple songs play

3, Expected Behavior) I expected the songs to play as normal and continuing for a while , instead now I expect the songs to play through for a small amount and then stop, look likes it's loading and claim that I have an unstable internet connection

4, Screenshots) 

![Screenshot_20240708_145504_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/175057809/0554e8fc-e292-4af8-bcb1-d861c7e59193)

5, log) Admittedly I don't know how to access the log itself but I hope the info I provided is somewhat enough to locate an issue

**Comment by Hyurun** [comment]
I'm facing exactly the same issue. In my case it's with only one track at a time but long ones (~1h30) it stopped after a couple of minute and I'm getting the same issue as shown above.
Don't know if it matter but those songs are downloaded.

**Comment by maxrave-dev** [comment]
Could you try to remove the download and download it again? May download be corrupted

**Comment by Moonwaffles22** [comment]
Forgot to check this earlier, I tried it and the problem seems to be fixed after I re-downloaded, thanks for helping :)
