### ISSUE TITLE
Podcast not working

### ISSUE THREAD

**Issue by Vivant420** [maxrave-dev/SimpMusic#435]
When tapping a podcast, this error comes up "Illegal input: Field 'isSelected' is required for type with serial name 'com.maxr..."

![Screenshot_20240709_010312_SimpMusic](https://github.com/maxrave-dev/SimpMusic/assets/164266591/3ecd14e1-1fe1-4aad-86a1-9f636b7c2e94)

**Comment by maxrave-dev** [comment]
Sorry for late, I fixed it in next build
