### ISSUE TITLE
Spotify Playlist!

### ISSUE THREAD

**Issue by Iamzainnnn** [maxrave-dev/SimpMusic#436]
What about Spotify Playlist implementation??
Just like Spotube Music Player 
Spotube use three API (Youtube, Piped, Saavn) for music streaming but I can also access Spotify playlist and play it. I hope you will also pay attention to this.

![Screenshot_2024-07-09-20-08-02-042_oss krtirtho spotube](https://github.com/maxrave-dev/SimpMusic/assets/89533747/282dc7f1-97d9-45de-af19-03a0f8a2d870)
![Screenshot_2024-07-09-20-13-10-799_oss krtirtho spotube](https://github.com/maxrave-dev/SimpMusic/assets/89533747/a9e7556e-fd60-448c-ae44-07cfe6761680)

**Comment by iwannet** [comment]
Use this https://github.com/linsomniac/spotify_to_ytmusic

**Comment by Iamzainnnn** [comment]
> Use this https://github.com/linsomniac/spotify_to_ytmusic

Thanks buddy but i want this in SimpMusic music player!
