### ISSUE TITLE
Quick pics functioning

### ISSUE THREAD

**Issue by ABHIRAJ770** [maxrave-dev/SimpMusic#439]
The quick pics are supposed to suggest music similar to the music we hear but in the simp music my quick pics just remain the same and never changes no matter how many times I refresh it

**To Reproduce**
Steps to reproduce the behavior: open the app and there you have it, the quick pics

**Expected behavior**
Suggest similar songs based on listening history

**Actual behaviour**
Suggesting the same songs from when I downloaded the app first time

**Comment by aneesh1122** [comment]
That's the problem with all the YT open source apps. They don't consider your listening history or your favorites. They just start a radio and suggest you similar songs. For youtube API you are just a unlogged user who has no listening history so it suggests you the same song everytime you start a radio.

**Comment by maxrave-dev** [comment]
Please log in to YouTube and turn on "Send back to Google" to enable

**Comment by aneesh1122** [comment]
> Please log in to YouTube and turn on "Send back to Google" to enable 

Does SimpMusic consider listening history to suggest songs in radio?

**Comment by maxrave-dev** [comment]
As I described on Readme page, when turn on this feature, all your listening history will be send back to Google. And this is good for recommending

**Comment by aneesh1122** [comment]
That's great. Is this possible? #395
