### ISSUE TITLE
Playlist not automatically on local playlists

### ISSUE THREAD

**Issue by CrazyWolf13** [maxrave-dev/SimpMusic#449]
**Describe the bug**
Playlists don't appear automatically on the Playlist section on android auto, I first have to manually mark each playlist as "local playlist"
This can be dangerous, as then one would need to use the phone, to  "activate" the playlist when actually wanting to drive with the car.

Can't there be an option to automatically add each playlist from "remote" to "local", has not to be default on, but at least a setting to opt-in to that?

Would be extremely helpful, thanks!

**To Reproduce**
1. Create a Playlist on youtube
2. Connect phone to car
3. Go to playlist tab and see not a single playlist is there
4. Notice, that you need to add every single playlist manually.
5. I have way too many playlists, so that took ages.

**Expected behavior**
A setting to automatically add every playlist from my account to local playlists.

Thanks you for this amazing work and app you created!

**Comment by maxrave-dev** [comment]
![image](https://github.com/user-attachments/assets/a8c6a5f2-dc55-4b1e-8118-fa38047fbc9f)

Tested in emulator device, I show full local playlists

**Comment by maxrave-dev** [comment]
Sync your local playlist to YouTube Music

**Comment by CrazyWolf13** [comment]
I'm not fully sure what you mean and why closed, so this feature is already implemented?

Because I cannot seem to find a setting called "sync local playlist with youtube music"

**Comment by maxrave-dev** [comment]
Click on your local playlist, click to three dot button at the right

**Comment by CrazyWolf13** [comment]
Yeah, I know that I can do it that way, but it was a feature request to add a toggle that make it **by default** so that every playlist on my youtube music automatically becomes a local playlist, so that if one has many hundred playlists, I do not have to add every single one manually to local playlist.

**Comment by maxrave-dev** [comment]
You can save your online to local too

**Comment by CrazyWolf13** [comment]
Oh yeak I know, sorry I do not know how to really explain this, but I mean like so that it happens automatically no pressing button just all playlist online<->local playlist for that a setting
