### ISSUE TITLE
Spotify login error(infinity load) 

### ISSUE THREAD

**Issue by Ctrl-sza18** [maxrave-dev/SimpMusic#463]
Describe the bug
Login to Spotify error infinity load

To Reproduce

Go to 'Home' tag
Click on 'Setting Icon' at top-right conner.
Scroll down to 'Spotify'
Click on 'Log in to Spotify'
Error: Infinity Load

The screenshot error below:
![Screenshot_20240801-160247.png](https://github.com/user-attachments/assets/1d030152-3c43-494e-a948-f9f04a1362d8)

**Comment by maxrave-dev** [comment]
Fixed #458
