### ISSUE TITLE
Lyrics bug 

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#468]
I faced a bug when the app shows wrong lyrics to the song. I think it's problem with Musixmatch. I'd love to pin the screen record but GitHub cancels uploading

**Comment by maxrave-dev** [comment]
Try nightly build

**Comment by maxrave-dev** [comment]
It is nested with Musixmatch

**Comment by adilurrhmn** [comment]
Okay 👍

**Comment by maxrave-dev** [comment]
@adilurrhmn https://github.com/maxrave-dev/SimpMusic/blob/jetpack_compose/app/src/main/java/com/maxrave/simpmusic/data/repository/MainRepository.kt#L1940

**Comment by Zdertis420** [comment]
> Try nightly build

Nah, it's not so crucial
