### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by Egapboi** [maxrave-dev/SimpMusic#470]
After the update of 0.2.3 the app is just not opening
![Screenshot_20240807_232508_SimpMusic](https://github.com/user-attachments/assets/c111cff4-dcb3-49af-91f5-01242bedea77)
![Screenshot_20240807_231547_SimpMusic](https://github.com/user-attachments/assets/237e27e2-d3f0-4077-b4ef-c8195f3db24b)

**Comment by 2010furs** [comment]
Mine too
