### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by Zdertis420** [maxrave-dev/SimpMusic#472]
After an update when I opened the app, it just doesn't work ![Screenshot_20240808_013301_SimpMusic.jpg](https://github.com/user-attachments/assets/02a7ae76-c02b-4fd9-9523-431aae06ecf4)

I'm trying to restart the app, but it doesn't help

There's the log ![Screenshot_20240808_013832_SimpMusic.jpg](https://github.com/user-attachments/assets/46bdcf0b-24c2-4cf3-89dd-c31f32b02429)

**Comment by Egapboi** [comment]
Yep same

**Comment by maxrave-dev** [comment]
#470 And I see the problem, will update a fix soon

**Comment by maxrave-dev** [comment]
https://issuetracker.google.com/issues/350432371

**Comment by Egapboi** [comment]
Thanks, i will downgrade the version for now
