### ISSUE TITLE
Lỗi không đăng nhập spotify facebook

### ISSUE THREAD

**Issue by skydragonhack** [maxrave-dev/SimpMusic#473]
**Describe the bug**

**To Reproduce**
1. Go to 'seting
2. Click on 'spotify'
3. Click on 'facebook'

**Expected behavior**

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.
![Screenshot_20240808-092931_SimpMusic](https://github.com/user-attachments/assets/74a41277-41f0-4d3a-9a00-0d2647676d82)

**Comment by maxrave-dev** [comment]
Because they block to use OAuth in Webview so can't
