### ISSUE TITLE
Crash at start after update

### ISSUE THREAD

**Issue by ABHIRAJ770** [maxrave-dev/SimpMusic#476]
Just look at this![Screenshot_20240808-170315.jpg](https://github.com/user-attachments/assets/53854221-e262-431a-8eb5-c71d992743b8)

![Screenshot_20240808-170544.jpg](https://github.com/user-attachments/assets/3bc4d867-ac2d-4b82-ad75-be018e17ad50)

**Comment by Egapboi** [comment]
Also happening ina android 11? I thought this was only happening to android 14
