### ISSUE TITLE
Illegal input: Field 'playlistld is required for type with 

### ISSUE THREAD

**Issue by Siriet-letter** [maxrave-dev/SimpMusic#488]
**No me deja reproducir mas canciones despues de buscar una cancion* 

![Screenshot_20240809_171809_SimpMusic](https://github.com/user-attachments/assets/d6684b76-998d-49e3-820b-4158a76a8016)
**

**To Reproduce**
...Illegal input: Field "playlistld"
is required for type with 

**Expected behavior**

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by maxrave-dev** [comment]
Fixed in nightly build
