### ISSUE TITLE
I will merge this into next build. Thanks for support me

### ISSUE THREAD

**Issue by WaldiSt** [maxrave-dev/SimpMusic#49]
I will merge this into next build. Thanks for support me

_Originally posted by @maxrave-dev in https://github.com/maxrave-dev/SimpMusic/issues/14#issuecomment-1663461274_

**Comment by WaldiSt** [comment]
... and the Polish language is still missing ...

**Comment by maxrave-dev** [comment]
please translate latest string xml because your translate is missing too many word
