### ISSUE TITLE
Lyrics translation bug?

### ISSUE THREAD

**Issue by Egapboi** [maxrave-dev/SimpMusic#495]
**Describe the bug**
It isn't showing the lyrics translation of all the lines.
I think its some musixmatch api problem, but i would be glad if u will look onto this, the new update fixed everything i mostly needed.

![Screenshot_20240813_193320_SimpMusic](https://github.com/user-attachments/assets/c30a53a4-00e4-4606-a7e9-95642ed27a95)

**Comment by maxrave-dev** [comment]
Please ask Musixmatch why they don't translate all lines. I don't know
