### ISSUE TITLE
Piped Support Feature Request

### ISSUE THREAD

**Issue by Wave6677** [maxrave-dev/SimpMusic#5]
Is Piped account and custom instance support planned for library backup? This app looks beautiful so far and I would love to see it work as a drop in replacement for any other proprietary app.

**Comment by maxrave-dev** [comment]
I think the Piped Instance I choose is working well now. I plan to develop a library for self-scraping YouTube Stream Data now.

**Comment by astarq** [comment]
It would be awesome if Piped account sync could be implemented, saving playlists created in-app to a user's Piped account. I believe that would make this the only open source YouTube Music app with sync!
