### ISSUE TITLE
Add a Crowdin Page

### ISSUE THREAD

**Issue by stepersy** [maxrave-dev/SimpMusic#51]
Hi! First of all I want to give you a huge thanks for this incredible app. SimpMusic is super useful and simple to use! I just want to ask if it's possible to add a Crowdin Page for the app, because it's easier for people instead of downloading Android Studio. I don't know if it's possible or if it's easier for you, but if you have time, please consider it! I'm interested in translating the app into Italian, but I don't have Android Studio on my PC and I don't have too much space to download it (I already have Visual Studio and Visual Studio Code). Thanks in advance, have a nice day!

**Comment by maxrave-dev** [comment]
Thanks for your recommend. I will try to create one

**Comment by d4f5409d** [comment]
Better would be Weblate to show FOSS some love.

**Comment by BluePixel4k** [comment]
Codeberg is hosting Weblate, maybe you can use it for translations:
https://translate.codeberg.org/about/

And BTW, Codeberg is also a good git service. In my opinion, better than GitHib because it's not Microsoft. 😅

**Comment by d4f5409d** [comment]
Lol

**Comment by BluePixel4k** [comment]
@maxrave-dev why did you choose Crowdin and not Weblate? 🥲

**Comment by maxrave-dev** [comment]
Crowdin is free, when I try to register Weblate, it required a web host, and i dont see any tutorial from internet
