### ISSUE TITLE
I'm Getting Some Errors in SimpMusic

### ISSUE THREAD

**Issue by sonisaltiner** [maxrave-dev/SimpMusic#547]
Hello, have a good day. I'm getting some errors in SimpMusic. Firstly, any song won't open and I get a "Timeout, check Internet Connection" notification.

https://github.com/user-attachments/assets/ec804090-0ffe-4765-ada9-c1aeedb6fef1

Secondly, a song is not available in my playlist, even though it is in my playlist.

![Screenshot_20241025_201346_com maxrave simpmusic](https://github.com/user-attachments/assets/e5cfee0a-e56c-4e3d-bbc9-befbe5d483c0)

Thirdly, I get a "New Updated Version Available" notification even though I downloaded the latest version from github.
![Screenshot_20241025_201429_com maxrave simpmusic](https://github.com/user-attachments/assets/71eb1658-5272-4a0e-8358-94136d36a147)
![Screenshot_20241025_201436_com maxrave simpmusic](https://github.com/user-attachments/assets/ffa3502a-6123-49e3-9144-6efbaaf6eba3)

The first and the second started happening a few days ago.

**Comment by Iliano101** [comment]
@sonisaltiner
For the last issue (Update popup) that issue is fixed in the Nightly build.
You can download it on the Readme.
![nightly](https://github.com/user-attachments/assets/c650d3eb-ba02-48b2-884d-dcd9c68e11dc)
The other issues may also be fixed by this version, but I have no guaranty on that.

**Comment by sonisaltiner** [comment]
Thank you for answering. The other problems were caused by youtube changing the bot detection algorithm(?)

**Comment by sonisaltiner** [comment]
@maxrave-dev

**Comment by Neutralix942** [comment]
I installed the Cloudflare 1.1.1.1 app, the problem was solved for me.

**Comment by mainajoya** [comment]
same problem v 1.6.0
