### ISSUE TITLE
Got Timed out even though I have good wifi connection 

### ISSUE THREAD

**Issue by BlueParrot789** [maxrave-dev/SimpMusic#549]
Every time I want to open a song I always get Timed out even though my wifi is still working fine. 

**To Reproduce**
1.open app
2.turn on the music
3.put it on looped (1)
4.Timed out

**Expected behavior**
Music played normally without being timed out

**Screenshots**
![Screenshot_2024-10-30-17-44-12-54_b4450e33c7076f102e79bbedaff38911](https://github.com/user-attachments/assets/daf54af1-e786-4319-82f6-d597952a3a4c)

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by tynicpal** [comment]
The same issue has been happening to me! Whenever I search a new artist and try to play different music it'll say "timed out, check internet connection". Also, it'll have "NA:NA" for the minutes:seconds while the song isn't loading. 
![Screenshot_20241031_121928_SimpMusic](https://github.com/user-attachments/assets/2f3e527b-7e12-49d4-af2d-aa4dc1a12cc6)

**Comment by ThinethSankalpa** [comment]
I have the same issue. Please fix this. I really love this app

**Comment by Kikoji-v** [comment]
Me too, I can't play music although i have good internet connection, i' ve tried so many times. Please fix this error

**Comment by ondrulin** [comment]
Same issue for me, please @maxrave-dev

**Comment by 5Two4** [comment]
It worked for me too. Thanks!

**Comment by abel200734** [comment]
> I found a fix (for me). You just have to sign in to your Google account in Settings. 👍

Ive signed  but didnt work

**Comment by Germaine33** [comment]
Also didn't work for me unfortunately 🥲

**Comment by mmk1102** [comment]
I don't know why, but for me, I need to sing OUT of my Google account (

**Comment by Tr43212** [comment]
> > I found a fix (for me). You just have to sign in to your Google account in Settings. 👍
> 
> Ive signed but didnt work

Maybe try to update the app to the lastest version?
