### ISSUE TITLE
Better Sync between youtube music

### ISSUE THREAD

**Issue by DuccTam276** [maxrave-dev/SimpMusic#560]
When i reinstall Simpmusic, I alway lost all local playlist
SO i request that i can import YouTube playlist to **Local ** playlist in Simpmusic. After that i can add music to playlist in Simpmusic. Like a **Local Playlist Cloud**

**Comment by maxrave-dev** [comment]
Firstly, open YouTube Music Playlist, click on three dot, you will see Save playlist to local playlist.

Secondly, you can create back up in settings. Btw, updating app don't delete app data.
