### ISSUE TITLE
While logged in, I can't add songs to a local synced playlist

### ISSUE THREAD

**Issue by androidghosh** [maxrave-dev/SimpMusic#597]
**Describe the bug**
While logged in, I can't add songs to a local synced playlist.

**To Reproduce**
1. login
2. copy a online playlist as local synced playlist
3. add a new song to that playlist
4. open the local playlist
5. no new song was added to local synced playlist
6. no new song was synced to yt music online playlist

**Expected behavior**
the song should be added to 1st the local synced playlist and then synced to yt music online playlist

**Screenshots**
https://www.dropbox.com/scl/fi/zgekeoji2d83w8l9wxefh/Screenrecorder-2024-12-02-13-29-51-358.mp4?rlkey=6be1extx62399bjl71u1f7rhl&st=u6rdboxz&dl=0

**Comment by maxrave-dev** [comment]
Fixed in latest build 😥
