### ISSUE TITLE
"Time out, check internet connection" error appears even when connected to the internet

### ISSUE THREAD

**Issue by gordaoescolas** [maxrave-dev/SimpMusic#622]
**Describe the bug**
When playing a song without cache on the device, the error message says that the connection timeout has been exceeded, even on 4G or WiFi. The connection to the YouTube/YT Music/youtube.com app is normal. Google Account login was also done again on both devices. It was tested on Motorola Edge 40 Neo and Samsung Galaxy A32. I also tried logging in with another Google Account, and the same error appears.

**To Reproduce**
1. Go to any song and play

**Comment by eddcm123** [comment]
Exactly the same here

**Comment by ardwiinoo** [comment]
I'm also having this issue, play any song or videos always show toast "Time out, Check Internet Connection" tested on 4G & Wifi the result is the same

**Comment by dudeman7665** [comment]
I got the same issue, I've been using this app for a while and this has never happened before. It still says it even when it's connected to the wifi

**Comment by maxrave-dev** [comment]
Fixed in nightly build

**Comment by maxrave-dev** [comment]
All of the YouTube Music app in Github have this issues, so I need to try hard to fix this

**Comment by maxrave-dev** [comment]
> > All of the YouTube Music app in Github have this issues, so I need to try hard to fix this
> 
> 
> 
> What is the cause of this problem?

YouTube Music changed API

**Comment by A1liya2ali3** [comment]
Has it been fixed yet?

**Comment by A1liya2ali3** [comment]
@maxrave-dev Can you please let us know how to use the app.i have had the same problem and tried doing everything recommend, but doesn't work? Also I downloaded nightly build and that also didn't work. Could you help please? Thanks

**Comment by maxrave-dev** [comment]
Fixed, check out the new release

**Comment by oktay675** [comment]
Ben de ahat hala devam ediyor sim sürümü kullanmama rağmen android  8.1

**Comment by oktay675** [comment]
> Sorun çözüldü, yeni sürüme göz atın.

Dostum uygulamaya bir göz atarmışım outer tune gibi diğer uygulamlar çıkarıyor ama simpmusic de calamamiyorum
