### ISSUE TITLE
white flashing when pausing/unpausing from notification in MIUI

### ISSUE THREAD

**Issue by github-user93** [maxrave-dev/SimpMusic#63]
I'm using redmi note 7 pro with miui 12.5.1 and android 10, and whenever i pause/unpause the player from notifications there is a white flashing

here is a recording
https://youtube.com/shorts/sqcIGaXSOeY?feature=share

**Comment by maxrave-dev** [comment]
> it sometimes flashes on its own, sometimes when pausing/unpausing

Did it flash with other music app?

**Comment by maxrave-dev** [comment]
Tested in HyperOS 1 still okey
