### ISSUE TITLE
Fix your app

### ISSUE THREAD

**Issue by Jimalkill10n** [maxrave-dev/SimpMusic#633]
At first I got an error that wouldn't let me download songs icdon't have a picture for it, but then after I reinstalled it, it started giving me an error when I tried to login with my YouTube. Not just that, it then started to not show anything but gray boxes, and when I tried to search something it wouldn't load.
![Screenshot_20241220-170657](https://github.com/user-attachments/assets/a2d333c6-3c12-4206-ad80-748d7c6bc99f)
![Screenshot_20241220-170727](https://github.com/user-attachments/assets/e8175cd7-8195-4770-9028-66226f107734)
![Screenshot_20241220-171241](https://github.com/user-attachments/assets/e4ff521a-8dbc-4eb6-b8fa-f36ab2f7e600)

**Comment by maxrave-dev** [comment]
Fixed, checkout new release
