### ISSUE TITLE
Unable to listen to music because of the timeout error. 

### ISSUE THREAD

**Issue by Junscript** [maxrave-dev/SimpMusic#634]
**Describe the bug**
I encounter a timeout error whenever I attempt to listen to music, preventing me from enjoying it. 

**To Reproduce**
1. Click on every song you see 
2. Time out error appears 

**Screenshot**

![Screenshot_2024-12-21-12-24-33-40](https://github.com/user-attachments/assets/5529208f-153f-43e9-adf6-33fd0ba71b81)

**Notice**
This error only appears when logged in the account.

**Comment by FinosO** [comment]
Lúc trc cũng bị giống vậy ko bt lm kiểu j mà bị lỗi này hoài

**Comment by Junscript** [comment]
> Lúc trc cũng bị giống vậy ko bt lm kiểu j mà bị lỗi này hoài

Cái lỗi này xuất hiện khi mà mình đăng nhập tk vào thôi chứ lúc đăng xuất hoặc để guest thì nó lại bình thường ngay

**Comment by Gu57avo** [comment]
I'm having the same issue, but it's not isolated too this app, it's happening in any app that plays yt music, like innertube.

**Comment by bach-tl** [comment]
Tui không đăng nhập cũng bị lỗi quá thời gian mà🥲

**Comment by maxrave-dev** [comment]
Fixed, check out new release
