### ISSUE TITLE
Switch source tracks

### ISSUE THREAD

**Issue by devanarayanan44** [maxrave-dev/SimpMusic#64]
Songs with music videos have two tracks, one with non-music segments and video thumbnail and another version without non music segments and proper album cover. so, add an option to switch between the tracks. spotube(another open-source app that uses spotify api and newpipe) has this option..

**Comment by maxrave-dev** [comment]
I will try, by the way, the MV and audio has 2 different videoId so too hard

**Comment by devanarayanan44** [comment]
or try adding sponsor block to cut the non music segments.
