### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [maxrave-dev/SimpMusic#651]
**Describe the bug**
There is no apk for 0.2.6. Could you please upload it? Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by maxrave-dev** [comment]
Please skip 0.2.6 version, it has bugs. Thanks 🥺

**Comment by linsui** [comment]
Got it! :)
