### ISSUE TITLE
Not able to save albums

### ISSUE THREAD

**Issue by Namra56** [maxrave-dev/SimpMusic#660]
**Describe the bug**

**To Reproduce**
1. Go to any album there is no option to like it or save it.

**Screenshots**
![Screenshot_2024-12-26-12-58-40-782_com.maxrave.simpmusic.jpg](https://github.com/user-attachments/assets/2e29506c-ce82-48b3-9e76-5a04b5398f28)

**Comment by bt4ibwem8** [comment]
This option should definitively be added
