### ISSUE TITLE
Korean language support

### ISSUE THREAD

**Issue by hsp1020** [maxrave-dev/SimpMusic#671]
I'm Korean. I translated all of the string.xml files into Korean. I'm posting on Issue because I can't use Pull request as a mobile user. I want you to reflect Korean support in the next version.

[strings.txt](https://github.com/user-attachments/files/18268765/strings.txt)
[arrays.txt](https://github.com/user-attachments/files/18268622/arrays.txt)
[plurals.txt](https://github.com/user-attachments/files/18268623/plurals.txt)

**Comment by maxrave-dev** [comment]
Thanks bro, I will add
