### ISSUE TITLE
Search filter tabs bugged

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#68]
1. Got to the search tab and search for something
2. Switch to a subcategory
3. Search for another song
4. Either have the old all search results and have to switch the tab to another and back or...
5. The other tabs at least partly have still the old search results and you have to refresh

(Search done with "ファジータウン" and "peggies weekend")

**Comment by maxrave-dev** [comment]
I have known this bug, thanks for reporting it. To avoid this, please wait until the search is done before switching filters. I will fix in next build
