### ISSUE TITLE
Some albums wont open

### ISSUE THREAD

**Issue by devanarayanan44** [maxrave-dev/SimpMusic#69]
The albums in the rock, pop... genre sections don't open.
![Screenshot_2023-08-27-17-54-50-467_com maxrave simpmusic](https://github.com/maxrave-dev/SimpMusic/assets/142968550/11311c8d-9196-4cc8-b7e8-3b98da910a15)

**Comment by maxrave-dev** [comment]
In my device, it's still working now

**Comment by devanarayanan44** [comment]
1. Opened the app.
2. scrolled down to genre section.
3. Selected pop.
4. Clicked on an album but it shows that (client request post...,).
