### ISSUE TITLE
Info about new releases by the followed artists

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#7]
I don't know if it's feasible but is there a way to be informed in some way about new releases from the artists you follow? Be it a notification or a hint through a dot or something similar. 

Thanks for the great app and your hard work.

**Comment by maxrave-dev** [comment]
To hard to observe the artist data because my server only scrape in unauthorized YouTube Music. I will find the way to observe this in future

**Comment by siggi1984** [comment]
> To hard to observe the artist data because my server only scrape in unauthorized YouTube Music. I will find the way to observe this in future

Is there already an opportunity to watch the artists or have they not had a chance to work on it yet?

Thank you for your hard work and time you put into this project.

**Comment by maxrave-dev** [comment]
Did you try to find notification in YouTube Music? May be YT music dont provide this. I see YouTube notification API but too much unnecessary notification from other subscription channel. So may be we need to wait YT Music

**Comment by Johndjk** [comment]
At least for me, just a button containing the "news" like Spotify would be more than great.

And thank you so much for developing the best open source music estream project I've ever seen.

After testing hundreds of apps over several years, this was the only one that made me replace Spotify.

With just a few more enhancements, it will be perfect. You're a hero, hahaha

**Comment by siggi1984** [comment]
You are the best

**Comment by siggi1984** [comment]
The function is mega, many thanks for that. I would still like to see a small change, namely that the latest notification/publication should always be at the top so that you don't always have to scroll down to the latest notification/publication.
