### ISSUE TITLE
If no connection skips endlessly through songs

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#70]
If the device got no internet connection, the app just skips endlessly and unstoppable through songs. I think this should only be done, when the song is for some reason really not available and if that's the case show a notice that and why the song is skipped.

**Comment by maxrave-dev** [comment]
Thanks for suggestion

**Comment by cd-FileX** [comment]
Also see my Enhancement list (#65) 9/2 for the thing with automatic song skipping
