### ISSUE TITLE
Playback not working

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#74]
The songs are often loaded correctly in one of the not player-views but not played back.
= You see the song all loaded showing with their data but on pressing the play button or on one song the song shows but doesn't load, on switching back away from player-view the player has no more information at all.

Seems like an error with the instance to me but I am not 100% sure about that.

**Comment by cd-FileX** [comment]
I will leave it in my enhancement list, to display an error on Piped API not working (Timeout or Gateway)

**Comment by maxrave-dev** [comment]
Yes, may be you need to change Piped Instance because Google blocked
