### ISSUE TITLE
Seems not to get all artists songs

### ISSUE THREAD

**Issue by cd-FileX** [maxrave-dev/SimpMusic#76]
For example for LONGMAN there would be "spiral" but it just displays Prelude.
I'm not sure how the shown content is managed, but if the video title differs from what is show in the app, shouldn't it be shown everywhere then?

**Comment by maxrave-dev** [comment]
All of SimpMusic's content depends on YouTube API, so sometimes, the content is incorrect. I don't know 😞😞😞

**Comment by cd-FileX** [comment]
You mean the YouTube Music API?

**Comment by cd-FileX** [comment]
Ah, so the content data is from YouTube Music API and the music from YouTube. Thus, YouTube has more songs than songs are registered on YT Music, causing ... 
No, if the titles that are shown in playlists and search are gotten from YouTube Music Data, then it doesn't matter if YT has more songs or not, it's always based on YT Music. 
So what you could do in this case would be, to search the artist, like you would do in the app's search, and pick out all the found songs where an artist is identical with the artist the user is currently looking at. Then you could sort them maybe into the shown song categories as well and thus overwrite YT Music's incorrect artist "database". 
However you should maybe create a cache or similar for that if it is a too large action and if possible only request the popularity of the song.
