### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [maxrave-dev/SimpMusic#79]
Hi @maxrave-dev, now that your app is listed on F-Droid.org for 2+ weeks, I'd usually remove it from my repo. I see you still have the badge pointing here – so I assume you want me to keep it here. Thanks to reproducible builds, that would be possible without "confusion" due to signature mismatches. So can you please tell me if you want me to keep it at IzzyOnDroid?

**Comment by maxrave-dev** [comment]
Please keep my app on IzzyOnDroid because Fdroid are updated my app too late, so IzzyOnDroid is best way to update app quickly

**Comment by IzzySoft** [comment]
Thanks to your app being set up for reproducible builds, this should be no issue – I've just set it to be kept here then, thanks! Yes, updates are a little faster with my repo as I simply have to grab your APK, while at F-Droid.org it must pass the "build cycle" (which usually takes 2..3 days; but sometimes a cycle takes a bit longer).

**Comment by moranronald912-png** [comment]
Porque se cierra
