### ISSUE TITLE
Replay Gain Normalization

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#8]
Feature description

Some songs are louder than others in a playlist. Replay Gain Normalization can be used to make them equally loud.

The variable volume is annoying and some songs aren't even audible unless you manually set the volume right for the song.

**Comment by maxrave-dev** [comment]
I don't think this problem caused by SimpMusic, please check again

**Comment by siggi1984** [comment]
simpmusic is no problem here. it would just be nice if all tracks had the same volume

**Comment by d4f5409d** [comment]
I agree, it'd cool to have ReplayGain.

**Comment by maxrave-dev** [comment]
@siggi1984 I see some tracks have a lower volume. I will try to resolve this problem in next build

**Comment by d4f5409d** [comment]
Cool! 😎 thanks
