### ISSUE TITLE
Lỗi không thể phát nhạc

### ISSUE THREAD

**Issue by Hanhne9** [maxrave-dev/SimpMusic#80]
Khi mình tìm kiếm thì nhạc vẫn lên bình thường nhưng khi nhấn vào thì không load được luôn.
![20230909_143902](https://github.com/maxrave-dev/SimpMusic/assets/108569208/30172ad5-d904-4b55-8fbc-581d20e99eec)

**Comment by maxrave-dev** [comment]
#74 Vào Cài đặt -> Đổi thực thể Piped 

Do Google thường xuyên block Piped nên xảy ra lỗi này. Chúc bạn có trải nghiệm tốt với SimpMusic
