### ISSUE TITLE
Share menu

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#9]
Make SimpMusic available in the "Share" menu.

This would make sharing from the left easier.

**Comment by maxrave-dev** [comment]
What do you mean exactly? Share is available in SimpMusic. You mean from YouTube, you click share button and SimpMusic appear in the Share Menu ?

**Comment by siggi1984** [comment]
> What do you mean exactly? Share is available in SimpMusic. You mean from YouTube, you click share button and SimpMusic appear in the Share Menu ?

Yes, that's exactly what I mean.
![215974370-b55fcab2-f799-4c6c-b49d-e49ebf654a1b](https://github.com/maxrave-dev/SimpMusic/assets/103368536/f49e7731-a71b-4beb-ad93-0f7d5da2ff07)

**Comment by maxrave-dev** [comment]
I see bro, I will add this feature in next build

**Comment by siggi1984** [comment]
Thanks, bro.
