### ISSUE TITLE
Piped Support Feature Request

### ISSUE THREAD

**Issue by siggi1984** [maxrave-dev/SimpMusic#92]
Would it be possible to support piped accounts and custom instances for library backups and then have your playlists cross-device?
This app looks great so far and I'd love to see it work as a replacement for any other proprietary music app.

**Comment by maxrave-dev** [comment]
Piped is so nice but it often is blocked by Google, so I am planning to remove Piped from SimpMusic. I am making SimpMusic syncing with Google account, YouTube, and YouTube Music. Please be patient, a bigger update coming soon. Thanks <3

**Comment by Terkyz** [comment]
Will there be no more Piped support or is it planned to be added again later? I really love SimpMusic but I don't like to give any information to Google, that's why I use Piped.

**Comment by Wave6677** [comment]
I was hoping there'd be custom instance support so I can use my self-hosted instance. this is really unfortunate :(
